options/ansi/generic/file-io.cpp, options/ansi/generic/stdio-stubs.cpp, options/ansi/generic/time-stubs.cpp, options/glibc/generic/sys-ioctl.cpp, options/internal/include/mlibc/sysdeps.hpp, options/linux/generic/poll-stubs.cpp, options/linux/generic/pty-stubs.cpp, options/linux/generic/sys-epoll.cpp, options/linux/generic/sys-inotify-stubs.cpp, options/linux/generic/sys-mount.cpp, options/linux/generic/sys-signalfd.cpp, options/linux/generic/sys-timerfd.cpp, options/posix/generic/dirent-stubs.cpp, options/posix/generic/fcntl-stubs.cpp, options/posix/generic/posix_signal.cpp, options/posix/generic/posix_stdlib.cpp, options/posix/generic/pthread-stubs.cpp, options/posix/generic/sys-mman-stubs.cpp, options/posix/generic/sys-socket-stubs.cpp, options/posix/generic/sys-stat-stubs.cpp, options/posix/generic/sys-time-stubs.cpp, options/posix/generic/sys-wait-stubs.cpp, options/posix/generic/termios-stubs.cpp, options/posix/generic/unistd-stubs.cpp, sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/qword/generic/file.cpp
Before this patch, sysdeps functions reported their errors in errno. Now, the error is reported in the return value and updating errno is done by the wrapper function that calls into sysdeps.
This approach has the advantage that mlibc can call sysdeps without having to worry about clobbering errno. Previously, annoying errno save/restore boilerplate would have been necessary.
Fixes #3.
=> internal: Report sysdeps errors in return value

options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/pthread-stubs.cpp
This patch implements recursive mutexes in `pthread_mutex_lock` and `pthread_mutex_unlock`.
=> Implement recursive pthread mutexes

options/posix/generic/posix_signal.cpp, options/posix/generic/sys-stat-stubs.cpp, options/posix/include/bits/posix/posix_signal.h, options/posix/include/glob.h, options/posix/include/sys/stat.h
Posix defines mknodat as taking 4 arguments, this change makes us conform to that.
=> Modifications for tar

options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/fcntl-stubs.cpp, options/posix/generic/pwd-stubs.cpp, options/posix/generic/unistd-stubs.cpp, sysdeps/managarm/generic/file.cpp
GNU Tar wants this function when making tar files.
However, it also fails on openat, getpwnam and maybe others which I haven't found yet.
I tried looking into that but I am not quite sure what to do with those functions, so I leave those up to the more experienced.
According to creat(2) the creat call is nothing more then a call to open with these 3 flags set.
=> Added required functions for GNU Tar

options/posix/include/sys/termios.h, options/posix/include/termios.h, options/posix/include/unistd.h, options/posix/meson.build
These changes are necessary for `gdbm` to compile
=> options/posix: Various header fixes

options/ansi/generic/ctype-stubs.cpp, options/ansi/generic/file-io.cpp, options/ansi/generic/stdlib-stubs.cpp
This PR implements the following:
- `towlower()` and `towupper()` char converters.
-  the flushing of all files when `fflush(NULL)` is called and on `exit()`
=> Various fixes for man-db

options/ansi/generic/stdio-stubs.cpp, options/ansi/generic/string-stubs.cpp, options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/unistd-stubs.cpp, sysdeps/managarm/generic/file.cpp
This PR adds the following:
- An implementation of the `setbuf()` function,
- An implementation of the `pread()` function,
- And a small bug fix to `strtok()`, related to strings which end on the requested delimiter.
=> Implementing various functions and a bugfix

options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/posix_stdlib.cpp, options/posix/generic/sys-stat-stubs.cpp, sysdeps/managarm/generic/file.cpp
This PR implements the following functions in posix:
- `ptsname()`
- `mkdirat()`
And stubs the following functions in posix:
- `fchmodat()`
This PR also unifies the code paths of `sys_mkdir()` and `sys_mkdirat()` in the managarm sysdeps.
=> options/posix: Implemented various functions

options/posix/generic/dirent-stubs.cpp
This change allows `cp` to copy directories correctly.
This fixes issue #67
=> options/posix: Implemented dirfd()

options/ansi/generic/stdio-stubs.cpp, options/internal/include/mlibc/sysdeps.hpp, sysdeps/managarm/generic/file.cpp
This change allows `mv` to work.
This closes issue #42
=> options/ansi: Implemented renameat()

abis/mlibc/in.h, options/ansi/generic/stdlib-stubs.cpp, options/ansi/generic/string-stubs.cpp, options/ansi/generic/time-stubs.cpp, options/ansi/generic/wchar-stubs.cpp, options/ansi/include/limits.h, options/ansi/include/setjmp.h, options/internal/x86_64/setjmp.S, options/linux/include/pty.h, options/posix/generic/libintl-stubs.cpp, options/posix/generic/spawn-stubs.cpp, options/posix/include/libintl.h, options/posix/include/sched.h, options/posix/include/spawn.h, options/posix/meson.build
These fixes also allow `gettext` to compile.
Python is functioning in script form, the interpreter doesn't respond to input, but the basic functionality is there
=> Various fixes to port python

options/posix/generic/pthread-stubs.cpp, options/posix/include/bits/posix/posix_stdlib.h
This PR also fixes a missing declaration of `ptsname`
=> options/posix: Implemented pthread_equal

options/posix/generic/netdb-stubs.cpp, options/posix/generic/posix_stdlib.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/bits/posix/posix_stdlib.h, options/posix/include/netdb.h, options/posix/include/sys/ipc.h, options/posix/include/sys/shm.h, options/posix/include/syslog.h, options/posix/include/unistd.h
This adds the following functions and definitions
For `xbps`:
- `getentropy()`, stubbed
- `vsyslog()`, stubbed
For `perl`:
- `h_errno`
- `gethostbyaddr()`, stubbed
- `drand48()`, stubbed
- `srand48()`, stubbed
- `struct ipc_perm`
- `struct shmid_ds`
=> Various functions to allow xbps and perl to compile

options/posix/generic/syslog-stubs.cpp, sysdeps/managarm/generic/file.cpp
This PR adds a stub for `vsyslog()` and catches bad fd's in managarms `sys_epoll_ctl()`
=> Small fixes to sysdeps and added a stub

options/posix/generic/arpa-inet-stubs.cpp, options/posix/generic/iconv-stubs.cpp
This pr allows wget to run, tested on managarm, working until the tcp requirement is there.
Furthermore, it stubs the `iconv` implementation, this causes a regression for `man-db`, it now hangs in an infinite loop
=> Various changes for wget

abis/mlibc/errno.h, abis/mlibc/stat.h, options/ansi/generic/errno-stubs.cpp, options/ansi/generic/stdio-stubs.cpp, options/ansi/include/errno.h, options/ansi/include/stdio.h, options/ansi/include/time.h, options/glibc/include/ar.h, options/glibc/meson.build, options/linux/generic/utmp-stubs.cpp, options/linux/include/utmp.h, options/linux/meson.build, options/posix/include/bits/posix/fd_set.h, options/posix/include/netinet/in.h, options/posix/include/sys/param.h, options/posix/include/sys/select.h, options/posix/include/sys/types.h, options/posix/include/sys/wait.h, options/posix/meson.build
This PR aims to let `sysklogd` and `make` compile. It adds the following:
- `setlinebuf()`
- `setutent()`, stubbed
- `getutent()`, stubbed
- `endutent()`, stubbed
Furthermore, this PR defines a couple of constants and adds an header as required for `sysklogd` and `make`
=> Implemented and stubbed various functions

options/ansi/generic/inttypes-stubs.cpp, options/ansi/generic/stdio-stubs.cpp, options/ansi/include/inttypes.h, options/internal/include/mlibc/sysdeps.hpp, options/linux/generic/sys-epoll.cpp, options/posix/generic/posix_stdlib.cpp, options/posix/generic/sys-select-stubs.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/bits/posix/fd_set.h, options/posix/include/bits/posix/posix_stdio.h, options/posix/include/sys/select.h, sysdeps/linux/generic/sysdeps.cpp, sysdeps/managarm/generic/file.cpp
This PR adds the following functions:
- `pselect()`, stubbed in to make `bc` happy
- `dprintf()`, stubbed in to satisfy a test program in `weston`
Furthermore, the following changes have been made:
- The macro `FD_SETSIZE` has been moved to `bits/posix/fd_set.h`. This change allows `git` to compile, but may not be ideal.
- The macro `SCNuMAX` has been defined, again, this makes `git` happy
~~This PR is blocked pending inclusion of pr managarm/managarm#178~~(Has been merged)
This PR is blocked pending inclusion of pr managarm/managarm#180
=> Various additions and fixes

abis/mlibc/signal.h, options/ansi/generic/stdio-stubs.cpp, options/ansi/generic/time-stubs.cpp, options/glibc/include/sys/ioctl.h, options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/pthread-stubs.cpp, options/posix/generic/sys-stat-stubs.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/generic/utime-stubs.cpp, options/posix/include/bits/posix/stat.h, options/posix/include/netinet/in.h, options/posix/include/pthread.h, options/posix/include/unistd.h, sysdeps/managarm/generic/file.cpp
This PR will hold the necessary changes to mlibc for `gdb` and `tcl` to build.
For now, these are:
- `pthread_attr_getscope()`, stubbed in, required by `tcl`
- `pthread_attr_setscope()`, stubbed in, required by `tcl`
- Defined `FIONBIO` for `gdb`
- Fixed overlapping signal constants (issue #27)
- Updated `sysconf()` with hardcoded values for `_SC_GETPW_R_SIZE_MAX` and `_SC_GETGR_R_SIZE_MAX`
- Moved the declarations of `htonl()` and friends to `netinet/in.h`, where they reside on Linux
Furthermore, some general improvements have been made:
- Implemented `utime()`, `utimes()`, `futimens()` and `utimensat()`
- Implemented `remove()`
- Defined `UTIME_NOW` and `UTIME_OMIT`
This PR is blocked on inclusion of managarm/managarm#181
=> Various additions for tcl, gdb and perl

sysdeps/managarm/generic/file.cpp
This fix allows sys_utimensat to compile when managarm/managarm#181 is merged and adds support for separate atime and mtime specifications.
As such, it is blocked on managarm/managarm#181
=> Small fix in sys_utimensat

options/posix/generic/pthread-stubs.cpp, options/posix/include/pthread.h
This PR adds 4 stubbed in pthread functions required for `libxshmfence` to compile.
=> Stubbed some pthread functions

options/ansi/generic/stdlib-stubs.cpp, options/ansi/generic/string-stubs.cpp, options/ansi/include/stdlib.h, options/posix/generic/posix_stdlib.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/bits/posix/posix_stdlib.h, options/posix/include/unistd.h, sysdeps/managarm/generic/file.cpp
This PR implements truncate for managarm and fixes some small bugs in `sysconf()`. It also updates `strerror()` with ENOEXEC.
This PR is blocked on managarm/managarm#190
=> Various small fixes

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/managarm/generic/socket.cpp
As discussed on discord, this PR converts the following syscalls to bragi:
- `sys_getuid()`
- `sys_setuid()`
- `sys_geteuid()`
- `sys_seteuid()`
- `sys_getgid()`
- `sys_setgid()`
- `sys_getegid()`
- `sys_setegid()`
- `sys_unlinkat()`
- `sys_stat()`
- `sys_mkfifoat()`
- `sys_linkat()`
- `sys_fchmodat()`
- `sys_utimensat()`
- `sys_rmdir()`
- `sys_inotify_add_watch()`
This batch should be done.
Blocked on managarm/managarm#191, but should be merged before directly afterwards as otherwise managarm won't boot
=> sysdeps/managarm: Convert sys_* to bragi

abis/mlibc/signal.h, options/ansi/generic/stdio-stubs.cpp, options/ansi/include/stdio.h, options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/sys/select.h, options/posix/include/sys/types.h, sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/socket.cpp
This PR fixes some small bugs that the compilation of xorg-server on managarm found.
Furthermore, it implements some functions that are required at runtime for `Xwayland`. It also adds `getentropy()`, and the corresponding syscall for managarm.
Blocked on managarm/managarm#195
Closes #117
=> Small fixes for xorg-server

sysdeps/qword/generic/generic.cpp
Fixed some misuse of an structure and casts, tested and it both builds and works
=> qword: Fix compilation for qword's sysdeps

sysdeps/lemon/generic/filesystem.cpp, sysdeps/lemon/generic/lemon.cpp, sysdeps/lemon/include/lemon/syscall.h
sysdeps/lemon: Stat no longer calls open, implemented rm/mkdir, (un)link, read_entries, open_dir, rename, set(e)uid and get(e)uid
=> Update lemon sysdeps

options/ansi/generic/time-stubs.cpp, options/ansi/include/ctype.h, options/posix/generic/unistd-stubs.cpp
This PR adds the following macro:
- `toascii`, This function, deemed deprecated by posix, is required for `libXaw` on managarm. It's implemented as a macro like glibc.
Furthermore, the following updates have taken place:
- `sysconf()` gained a response for the obsolete `_SC_CLK_TCK` call.
- `localtime_r()` and `gmtime_r()` neglected to set `tm_gmtoff` before returning, this lead to the use of uninitialized variables in python, crashing it.
=> Some small fixes

abis/mlibc/signal.h, options/posix/include/sys/socket.h
This ABI breaking change is needed for `tcl` to compile. It also fixes #27 
This PR also includes an ABI breaking change regarding the `sockaddr` struct, we now match glibc's behavior regarding sa_data's array size. This satisfies `python` enough to build the `_socket` module
=> ABI: Fix overlapping signal constants and struct sockaddr

abis/mlibc/resource.h
i used this site as a source: https://www.gnu.org/software/libc/manual/html_node/Resource-Usage.html
=> abis/mlibc: add missing struct rusage members

options/linux/include/linux/netlink.h, options/posix/generic/dirent-stubs.cpp
This PR adds the following:
- 3 new `NETLINK_` constants, required by `python`'s socket module.
Furthermore, the following has been updated:
- `rewinddir()` has been implemented by `lseek()`.
=> Small additions

options/elf/include/elf.h, options/rtdl/generic/linker.cpp, options/rtdl/generic/main.cpp
This PR adds various new structs required by cmake, it also fixes the declaration of Elf64_Dyn to match glibc and adjusts rtdl to reflect this.
=> elf: Various Elf32 fixes required by cmake

abis/mlibc/signal.h
During the refactor, some signals got left out while they are definitely needed. This caused issues with the eudev build on managarm. This PR fixes that
=> abis/mlibc: Add missing signal numbers

options/ansi/generic/environment.cpp, options/posix/generic/unistd-stubs.cpp
This PR fixes a bug in the handling of environment variables found while working with `gtk3` on managarm. Furthermore, it implements `lockf()` like musl.
This PR fixes #169
=> Implement lockf and fixed a bug in environment handling

abis/mlibc/socket.h, options/linux/generic/linux-unistd.cpp, options/linux/include/bits/linux/linux_unistd.h, options/linux/meson.build, options/posix/generic/net-if-stubs.cpp, options/posix/generic/sys-socket-stubs.cpp, options/posix/generic/sys-uio.cpp, options/posix/generic/termios-stubs.cpp, options/posix/include/sys/socket.h, options/posix/include/sys/uio.h, options/posix/include/termios.h, options/posix/include/unistd.h
This PR aims to stub and provide functions and structs as requested by `libuv` and `cmake`. To accomplish this, the following struct has been added:
- `struct mmsghdr`.
Furthermore, the following functions have been added and stubbed:
- `cfmakeraw()`.
- `dup3()`,
- `recvmmsg()`,
- `sendmmsg()`,
- `preadv()`,
- `pwritev()`.
- All the functions in the net-if-stubs.cpp file located in options/posix are now declared with `extern "C"` linkage to satisfy `libuv`.
=> Various libuv and cmake related changes

options/internal/x86_64/setjmp.S
The definition of `longjmp` specifies that it must make `setjmp` return 1 if the passed value is 0, else it must make it return said value. The current `x86_64` implementation does not take that into account, now it does.
Source: https://pubs.opengroup.org/onlinepubs/009695399/functions/longjmp.html, more specifically
```
After longjmp() is completed, program execution continues as if the corresponding invocation of setjmp() had just returned the value specified by val. The longjmp() function shall not cause setjmp() to return 0; if val is 0, setjmp() shall return 1.
```
=> setjmp: Fix non spec-compliant longjmp for x86_64

abis/managarm/auxv.h, options/posix/include/sys/un.h
This PR adds the following two defines to satisfy `p11-kit`.
- `AT_SECURE` is defined for Managarm,
- `SUN_LEN` macro has been added.
=> Add some defines needed for p11-kit

abis/mlibc/fcntl.h, options/posix/generic/pthread-stubs.cpp, options/posix/include/pthread.h, sysdeps/managarm/generic/time.cpp
While updating `weston` for Managarm, the following changes were required:
New functions:
- `pthread_setname_np()`, stubbed.
- `pthread_getname_np()`, stubbed.
New defines:
- 4 fcntl defines related to `mmap()` and friends have been defined.
Updates:
- In Managarm sysdeps, `clock_getres()` now handles `CLOCK_MONOTONIC_RAW` like `CLOCK_MONOTONIC` instead of panicking (`CLOCK_MONOTONIC_RAW` is a Linux extension).
=> Various changes needed to update weston

options/linux/generic/sys-random-stubs.cpp
This PR implements `getrandom` via `sys_getentropy()`, this should remove the `mlibc: getrandom() is a no-op` message shown on managarm boot.
=> options/linux: Implement getrandom

options/posix/generic/posix_signal.cpp, options/posix/generic/spawn-stubs.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/bits/posix/posix_signal.h, options/posix/include/spawn.h, options/posix/include/unistd.h, sysdeps/linux/generic/cxx-syscall.hpp, sysdeps/linux/generic/sysdeps.cpp, tests/meson.build, tests/posix/posix_spawn.c
This PR implements `posix_spawn` in the same way that musl does. Furthermore, it fixes some off-by-one bugs in some signal related functions, adds a test for `posix_spawn` and adds several linux syscalls to fulfill the test.
This PR is not really blocked on managarm/managarm#243 but should be merged together with it, to avoid breaking managarm
=> options/posix: Implement posix_spawn

options/ansi/include/locale.h
This fixes several gnulib tests that are currently breaking coreutils and friends from compiling.
=> options/ansi: Add missing locale define

options/posix/generic/spawn-stubs.cpp, options/posix/generic/unistd-stubs.cpp
This PR implements the following functions:
- `posix_spawnattr_init()`,
- `posix_spawnattr_destroy()`,
- `posix_spawnattr_setflags()`,
- `posix_spawnattr_setsigdefault()`,
- `posix_spawnattr_setsigmask()`,
- `posix_spawnattr_setpgroup()`,
- `posix_spawn_file_actions_init()`,
- `posix_spawn_file_actions_destroy()`,
- `posix_spawn_file_actions_adddup2()`,
- `posix_spawn_file_actions_addclose()`,
- `posix_spawn_file_actions_addopen()`,
- `posix_spawnp()`.
=> options/posix: Implement spawn-related helpers

options/ansi/generic/stdlib-stubs.cpp, options/ansi/include/ctype.h, tests/ansi/abs.c, tests/meson.build
These are used by some software such as NASM.
=> options/ansi: Implement abs, labs and llabs, include <bits/feature.h> in ctype.h to fix POSIX locale ctype extensions

options/ansi/generic/time-stubs.cpp, options/ansi/include/time.h
This PR adds the following functions:
- `asctime_r()`, required by `claws`,
- `ctime_r()`, required by `claws`.
Furthermore, the following functions got implemented:
- `clock()`, required by `zstd`,
- `timespec_get()`, required by `zstd`.
=> options/ansi: Add several time related functions

options/posix/generic/posix_locale.cpp, options/posix/include/bits/posix/posix_locale.h
=> Stub out duplocale

sysdeps/managarm/generic/file.cpp
This PR is required after merging managarm/managarm#244, otherwise weston will fail to boot.
Blocked on managarm/managarm#244
=> sysdeps/managarm: Fix sys_openat after the PathResolver refactor

sysdeps/managarm/generic/file.cpp
This fixes certain applications failing on unhandled ioctl's on writer side fifo's
Blocked on (and directly after) managarm/managarm#245
=> sysdeps/managarm: Handle EINVAL in ioctl(TIOCGWINSZ)

options/linux/include/asm/ioctls.h
This PR adds a ioctl define needed for `cmatrix`
=> options/linux: Add TIOCSTI

options/ansi/generic/time-stubs.cpp, options/posix/generic/syslog-stubs.cpp, options/posix/include/syslog.h, tests/ansi/strftime.c, tests/meson.build
This PR implements `syslog()` and `vsyslog()` like musl, with the added extension that should the `connect()` call to the syslog socket fail, we fall back to using `mlibc::infoLogger()`.
=> options/posix: syslog improvements

options/posix/generic/strings-stubs.cpp, options/posix/include/strings.h, tests/ansi/strchr.c, tests/ansi/strrchr.c, tests/meson.build, tests/posix/index.c, tests/posix/rindex.c
The recent addition of `index` and the subsequent patch update for `xorg-proto` broke `xorg-server` on managarm, this PR fixes that issue.
The following functions have been added:
- `rindex()`, the reverse variant of `index()`.
=> options/posix: Add rindex

options/glibc/generic/shadow-stubs.cpp, options/glibc/include/shadow.h, options/linux/generic/linux-unistd.cpp, options/linux/generic/utmpx.cpp, options/linux/include/asm/ioctls.h, options/linux/include/bits/linux/linux_unistd.h, options/linux/include/ifaddrs.h, options/linux/include/utmpx.h, options/linux/meson.build, options/posix/generic/grp-stubs.cpp, options/posix/generic/search.cpp, options/posix/include/grp.h, options/posix/include/net/if.h, options/posix/include/search.h, options/posix/include/sys/param.h, options/posix/include/sys/ttydefaults.h, options/posix/include/unistd.h, tests/meson.build, tests/posix/search.c
This PR adds the following stubs:
- `udwtmpx()`,
- `endutxent()`,
- `setutxent()`,
- `getutxent()`,
- `pututxline()`,
- `utmpxname()`,
- `vhangup()`,
- `getgrouplist()`,
- `twalk()`,
- `tdestroy()`,
- `getspnam()`.
This PR implements the following function:
- `tfind()`,
- `tsearch()`.
Furthermore, the following defines and structs were added:
- `struct utmpx`,
- several `utmpx` related defines,
- `MAXNAMELEN`,
- 2 sysconf defines,
- `struct ifaddrs`,
- `TTYDEF_SPEED`,
- 3 `net/if.h` related defines,
- `TIOCMGET` ioctl define,
- the `VISIT` enum.
=> Various stubs and defines for util-linux

options/linux/include/linux/input-event-codes.h
This define is required by `eudev` version 3.2.10.
=> options/linux: Add BTN_DIGI define

options/ansi/generic/string-stubs.cpp, options/posix/generic/sys-stat-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/managarm/generic/file.cpp
This PR is the mlibc counterpart of managarm/managarm#248 and provides an implementation of `sys_mknodat()` for managarm, wires `mknod()` to `mknodat()`, improves error handling in some managarm sysdeps and adds a string for ENOSPC to `strerror()`.
Blocked on and to be merged shortly after managarm/managarm#248
Fixes #94
=> sysdeps/managarm: Implement sys_mknodat

options/ansi/generic/string-stubs.cpp, options/ansi/include/string.h, options/posix/generic/posix_string.cpp, options/posix/include/bits/posix/posix_string.h
Fix the build by moving this function to the POSIX option.
=> Fix ANSI-only build after strcasestr() implementation

options/ansi/generic/file-io.cpp
When doing large (causing a buffer flush) consecutive writes we call ``lseek(fd, 0 SEEK_CUR)`` for every flush operation, essentially doubling the needed syscall overhead. So we should only lseek when ``__io_offset != __dirty_begin``.
=> options/ansi: avoid uneeded lseek()'ing in file writes

sysdeps/managarm/generic/file.cpp
This PR fixes the handling of partial writes in `sys_write()`, adds handling of EAGAIN in `sys_msg_send()` and `sys_write()` and adds code to handle `FIONBIO` to `sys_ioctl()`.
This PR is blocked on managarm/managarm#253
=> sysdeps/managarm: Various netstack-related fixes

options/posix/generic/termios-stubs.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, options/posix/include/termios.h, options/posix/include/unistd.h, sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/qword/generic/generic.cpp
This PR implements various process group functions for managarm.
At the moment the following functions are implemented (most of these are actualy sysdeps for managarm):
- `getpgid()`,
- `setpgid()`,
- `tcgetpgrp()`.
- `tcsetpgrp()`,
- `getpgrp()`,
- `getsid()`,
- `setpgrp()`,
- `ctermid()`.
This PR is blocked on managarm/managarm#250
=> Implement various process group functions

options/ansi/include/limits.h
Glib 2.68.0 and higher seems to require this define. It's value matches Linux.
=> options/ansi: Add _POSIX_HOST_NAME_MAX define

sysdeps/managarm/generic/file.cpp
This fixes X apps crashing on startup
=> sysdeps/managarm: Handle "dismiss" errors for ioctls

.github/workflows/ci.yml, ci/bootstrap.yml, ci/dripos.cross-file, ci/lemon.cross-file, ci/qword.cross-file, meson.build
This PR adapts mlibc to the changes in cxxshim that are required to build managarm with gcc 10. It is thus blocked on everything listed in manangarm/bootstrap-managarm#100 and can only be merged if all the blockers in that PR (with exception of the managarm one) is already merged. After this PR is merged, managarm/bootstrap-managarm#100 _needs_ to be merged to avoid build failures.
=> build: Bump c++ standard to c++20

abis/mlibc/gid_t.h, abis/mlibc/uid_t.h, options/posix/include/bits/posix/id_t.h, sysdeps/lemon/generic/lemon.cpp
On Linux (and apparently everywhere else), these are unsigned types.
=> abis/mlibc: Change uid_t, gid_t and id_t to unsigned

options/rtdl/generic/linker.cpp, options/rtdl/generic/linker.hpp, options/rtdl/generic/main.cpp
This PR implements the missing case for when `dladdr()` can't find the symbol, and should return the DSO that it should be in. Required for `clang` to function.
(Partially) fixes #211
=> rtdl: Implement the case in dladdr where the symbol cannot be found

options/linux/generic/sys-random-stubs.cpp, options/posix/generic/unistd-stubs.cpp, sysdeps/managarm/generic/file.cpp
This PR moves the size check from the managarm sysdep (which is the only platform that implements `sys_getentropy`) to the actual `getrandom()` function.
=> Small fix related to getrandom

options/glibc/include/memory.h, options/glibc/meson.build, options/linux/include/sys/syscall.h, options/linux/meson.build, sysdeps/linux/generic/sysdeps.cpp
This PR adds various headers and syscalls for the Linux port, enabling it to compile and run `OpenSSL` commands.
The following headers have been added:
- `memory.h`, installed when the ansi option is enabled,
- `sys/syscall.h`, a dummy header is installed when the linux option is enabled.
Furthermore, this PR implements the following syscalls for the Linux port:
- `sys_getuid()`,
- `sys_geteuid()`,
- `sys_getgid()`,
- `sys_getegid()`.
=> Various Linux fixes for OpenSSL

options/ansi/generic/time-stubs.cpp
This PR stubs `strptime()` as a temporary solution, allowing `xbps-install` to work on Managarm.
=> options/ansi: Stub strptime

options/ansi/generic/signal-stubs.cpp, sysdeps/lemon/generic/filesystem.cpp, sysdeps/lemon/generic/lemon.cpp, sysdeps/lemon/generic/signals.cpp, sysdeps/lemon/generic/sockets.cpp, sysdeps/lemon/include/lemon/syscall.h, sysdeps/lemon/meson.build
This is in line with the POSIX spec.
Programs such as zsh may pass an invalid signal number and crash on EINVAL.
Also updated lemon sysdeps.
=>  options/ansi: Return SIG_ERR instead of panic when sys_sigaction fails in signal()

options/posix/generic/pthread-stubs.cpp, options/posix/generic/pwd-stubs.cpp, options/posix/include/pthread.h, sysdeps/linux/generic/sysdeps.cpp, tests/meson.build, tests/posix/pthread_cond.c, tests/posix/pwd.c
- options/posix: fill pw_passwd in getpw{nam,uid}
- options/posix: stub pthread_attr_init, enable pthread_cond_{wait, broadcast}
After this PR, it just crashes on `pthread_detach`.
=> Various fixes for `exa`

options/ansi/generic/file-io.cpp, options/ansi/generic/wchar-stubs.cpp, options/ansi/include/mlibc/file-io.hpp, options/internal/generic/charcode.cpp, options/internal/include/mlibc/charcode.hpp, options/posix/generic/pthread-stubs.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/managarm/generic/file.cpp, tests/ansi/wcsrtombs.c, tests/meson.build, tests/posix/pthread_cancel.c
This PR adds more error handling code to several of Managarms sysdeps and adds proper handling to `wcsrtombs()` and `wcsrntombs()` when the first argument is NULL. This also allows the python dynamic interpreter to work on Managarm. Furthermore, a bug in the pthread cancel implementation was found and fixed,  `_CS_GNU_LIBC_VERSION` is now handled in `confstr()` and the buffer mode of `stderr` is now correctly set.
Blocked on managarm/managarm#351, but should be merged at the same time to avoid build failures.
=> Python fixes

options/posix/generic/grp-stubs.cpp, options/posix/generic/unistd-stubs.cpp
This PR stubs `initgroups()` and implements `execle()` like musl. With this, I can run `su --login managarm` on Managarm to become the managarm user.
=> posix: Implement and stub more functions for shadow to function

options/posix/generic/posix_stdlib.cpp, options/posix/include/bits/posix/posix_stdlib.h
This is required for `ninja` to compile. I thought this was already upstreamed in a different PR but apparently I was wrong.
=> options/posix: Stub getloadavg

options/glibc/generic/shadow-stubs.cpp, options/glibc/include/shadow.h, options/linux/generic/linux-unistd.cpp, options/linux/generic/utmp-stubs.cpp, options/linux/include/bits/linux/linux_unistd.h, options/linux/include/utmp.h
Does what it says on the tin. However, `getdtablesize()` does only return the arbitrary value that sysconf returns.
=> Add several stubs and implement `getdtablesize()`

options/ansi/include/assert.h
Required for newer mesa builds.
=> options/ansi: Add the static_assert convenience define

meson.build
This saves us a risky join by space and cleans up the code to an extent
Co-Authored-By: Eli Schwartz <eschwartz@archlinux.org>
=> meson: use meson builtins instead of shell

options/linux-headers/include/linux/fb.h, options/linux-headers/meson.build
Adds a missing header for Linux fbdev interface. Used by Vinix and needed for things like weston fbdev backend and etc.
=> options/linux-headers: add linux/fb.h

options/ansi/generic/stdio-stubs.cpp, options/rtdl/generic/linker.cpp, tests/posix/getdelim.c
This fixes minor issues with `getdelim` that prevented `xbps-reconfigure` from running for some. Fallthroughs were annotated or `break`s added, where appropriate.
=> Fix getdelim and annotate fallthroughs

sysdeps/managarm/generic/socket.cpp
During testing on Managarm, a problem with a stubbed return for getsockopt was found. This PR fixes that by returning an actual success code and passing the value the way it is expected. It also adds 3 other getsockopt stub returns, pleasing several users.
=> Fix some getsockopt issues

options/linux-headers/include/asm/ioctls.h
After merging this, Aero can drop the hardcoded hack from their sysdeps.
=> linux-headers: Add TCSETSF

options/glibc/include/netinet/in_systm.h, options/glibc/meson.build
`cups` really wants `netinet/in_systm.h` to exist, but it doesn't need anything from it. Provide an empty file to make it happy.
=> options/glibc: Add empty in_systm header to fix the cups port

options/glibc/meson.build, options/linux-headers/include/linux/ip.h
This PR fixes an error in 060b995c318c2fb08e88525815a32719f5236b81 where the installation directory of `in_systm.h` was inadvertently changed to go to the wrong location, breaking the `cups` port. It also adds a `struct iphdr` to the `ip.h` linux kernel header in order to satisfy `qemu` picking up said header and wanting to use its contents.
=> Small fixes to fix CI

options/linux-headers/include/linux/netlink.h
=> options/linux-header: Add nlattr struct to netlink.h

options/posix/generic/posix_signal.cpp
Calling killpg with a pid of 1 or less is undefined behavior, implemented here as setting EINVAL as musl does
=> Implement killpg

abis/linux/x86_64/wait.h, abis/mlibc/wait.h, options/linux/generic/sys-fsuid.cpp, options/linux/include/sys/fsuid.h, options/linux/include/sys/mount.h, options/linux/meson.build
This PR adds some definitions and 2 new stubs that allows `fuse3` to compile, provided some parts related to capabilities and cloning with namespaces are `#ifdef` out.
=> Various fixes to allow fuse3 to compile

options/ansi/generic/stdio-stubs.cpp
This PR implements `scanf` using the same code as `fscanf`.
The only difference is that instead of passing the file stream argument, it passes `stdin` to `vfscanf`.
=> options/ansi: Implement scanf

options/ansi/include/inttypes.h, options/linux/generic/malloc.cpp, options/posix/generic/sched-stubs.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/netinet/tcp.h, options/posix/include/sched.h, options/posix/include/unistd.h, sysdeps/managarm/generic/file.cpp
This PR adds a few small stubs and defines that `ffmpeg` uses. It also adds a missing error handling case to Managarm's `sys_ftruncate()`.
=> Various additions for ffmpeg to compile

options/posix/generic/posix_string.cpp, tests/meson.build, tests/posix/memrchr.c
This PR implements `memrchr()` which is apparently used by `grep` now that is available.
=> options/posix: Implement memrchr

options/rtdl/generic/linker.cpp, options/rtdl/generic/linker.hpp, options/rtdl/generic/main.cpp, tests/meson.build, tests/posix/pthread_thread_local.c
Fixes managarm/mlibc#389.
This still leaves the issue of managarm/mlibc#393, which might be trickier to fix.
=> rtdl: initialize tls objects for new threads

options/posix/generic/sys-mman-stubs.cpp, options/posix/include/sys/mman.h
Missed this for LLVM 14 as I had this locally already. Hotfixes LLVM 14 on xbbs.
=> Stub madvise and define MADV_DONTNEED

sysdeps/managarm/generic/file.cpp
In the recently merged managarm PR 397 a specific NOT_A_TTY error got added to the POSIX protocol. This PR changes sys_ttyname() to not just check for BAD_FD as was done previously, but also properly check for NOT_A_TTY and return the correct error code.
=> Make sys_ttyname() check for NOT_A_TTY

options/posix/include/sys/mman.h
This fixes the Managarm builds for `mednafen` and `qemu`.
=> options/posix: Define MADV_SEQUENTIAL and MADV_WILLNEED

options/glibc/include/endian.h
Otherwise anyone including it will get build errors from the lack of __bswap family functions
=> options/glibc: Include byteswap.h in endian.h

options/posix/generic/sys-time-stubs.cpp, options/posix/include/sys/time.h
While making the first 2 args `const` is not required by the spec, some code seems to assume that they are. Because an implementation should not modify them anyways, making them const is justified to avoid patching.
=> options/posix: make timer{add,sub} take 2 const args

options/posix/generic/posix_locale.cpp
This follows the precedent of the other locale functions and allows sway to run.
=> options/posix: make freelocale a noop

options/ansi/include/math.h
This issue came to light when compiling `libvpx`, and this seems to fix the problems.
=> options/ansi: Avoid multiple definition errors in math.h

options/posix/include/sys/sem.h
This fixes a ci build failure for `perl`.
=> options/posix: Add GETALL and SETALL

ci/bootstrap.yml, meson.build
This allows people to have multiple build folders on the go at the same time (e.g one for Managarm and one for testing on Linux).
Also gets rid of the meson complaint about c++20 language settings.
=> meson: find frigg and cxxshim via pkg-config

meson.build, options/internal/aarch64-include/mlibc/thread.hpp, options/internal/include/mlibc/thread.hpp, options/internal/x86_64-include/mlibc/thread.hpp, options/lsb/generic/tls.cpp, options/rtdl/generic/linker.cpp, options/rtdl/generic/main.cpp, options/rtdl/include/mlibc/rtdl-abi.hpp
- use `get_current_tcb` instead of `getCurrentTcb`
- move `__abi_tls_entry` to header
=> rtdl: refactor `getCurrentTcb` and `__abi_tls_entry`

options/ansi/generic/stdlib-stubs.cpp, tests/ansi/alloc.c, tests/meson.build, tests/posix/posix_memalign.c
`posix_memalign` requires that align is a power of two multiple of `sizeof(void *)`, but C11's `aligned_alloc` does not. Hence we must make sure the alignment is adjusted correctly when passing to `posix_memalign`.
We also add an extra check for the case that a bad alignment is passed to `aligned_alloc`.
Also adds some regression tests for these cases.
=> options/ansi: fix alignment checks in aligned_alloc

options/internal/generic/debug.cpp, options/internal/include/mlibc/debug.hpp
This should make some assertion failures more readable.
=> options/internal: increase log stack buffer size

abis/linux/x86_64/access.h, abis/mlibc/access.h, options/posix/include/unistd.h, sysdeps/aero/include/abi-bits/access.h, sysdeps/aero/meson.build, sysdeps/dripos/include/abi-bits/access.h, sysdeps/dripos/meson.build, sysdeps/lemon/include/abi-bits/access.h, sysdeps/lemon/meson.build, sysdeps/linux/include/abi-bits/access.h, sysdeps/linux/meson.build, sysdeps/managarm/include/abi-bits/access.h, sysdeps/managarm/meson.build, sysdeps/qword/include/abi-bits/access.h, sysdeps/qword/meson.build, sysdeps/sigma/include/abi-bits/access.h, sysdeps/sigma/meson.build, tests/ansi/longjmp.c, tests/meson.build, tests/posix/access.c
Fixes the ABI for `access` on Linux. Also adds an `access` test (and one for `longjmp` too, because why not)
=> abis: place {F,W,R,X}_OK in abi-bits

options/posix/generic/pthread-stubs.cpp
As discussed on discord [here](https://discord.com/channels/678608576151027731/678613510237978625/973180749144539156), I've fixed the issue with `pthread_mutex_trylock()`. Should be good to go now.
=> options/posix: Fix incorrect deadlock detection in pthread_mutex_trylock

options/ansi/generic/wchar-stubs.cpp
This PR fixes a TODO in `mbrtowc` related to the `wcp` argument being a nullptr.
=> options/ansi: Implement the !wcp case in mbrtowc

sysdeps/managarm/generic/file.cpp
Chromium relies on `madvise()` returning 0, which we can only satisfy if we stub the actual sysdep.
=> sysdeps/managarm: Stub sys_madvise

sysdeps/managarm/generic/time.cpp
This fixes a crash with `links` on Managarm.
=> sysdeps/managarm: Stub CLOCK_MONOTONIC_COARSE support in sys_clock_get

options/posix/generic/unistd-stubs.cpp
After merging #445, some warnings remained. This PR fixes two of them.
=> options/posix: Fix warnings in alarm

abis/mlibc/in.h, options/linux-headers/include/asm/ioctls.h, options/linux-headers/include/linux/sockios.h, options/linux/generic/ifaddrs.cpp, options/linux/include/ifaddrs.h, options/linux/meson.build, options/posix/include/bits/posix/posix_signal.h, options/posix/include/dlfcn.h
This PR adds various constants, defines, structs and functions that `wine` requires. It certainly isn’t everything but this can already get reviewed and merged.
Has an abi-break counterpart in #452, which is not required for this to be merged, but is required for wine.
Also includes some fixes for Chromium incidentially, so part of the Chromium on Managarm project.
=> Various fixes on the way to wine

options/posix/generic/services.cpp, tests/posix/getservbyname.c, tests/posix/getservbyport.c
About the asserts, quoting the man page: `Port numbers are assigned by the IANA (Internet Assigned Numbers Authority), and their current policy is to assign both TCP and UDP protocols when assigning a port number. Therefore, most entries will have two entries, even for TCP-only services.`
In the loop, the name length did not get reset; this caused a reproducible segfault in local testing for me and @64.
=> tests: fix getservby{name,port}

options/linux-headers/include/linux/rtnetlink.h
This PR adds a missing enum to `rtnetlink.h`, which is used by Chromium and parts of the Managarm netstack.
=> options/linux-headers: Add rt_class_t enum

options/posix/generic/sys-select-stubs.cpp, options/posix/include/sys/select.h
This PR refactors FD_SET and friends to be consistent with the way glibc defines them, which makes wine happy during compilation. No functional changes are made.
Abi break counterpart of #374
=> options/posix: Refactor FD_SET and friends to work with wine

options/posix/generic/unistd-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/managarm/generic/file.cpp
This PR implements `pwrite()` as a sysdep, and adds an implementation of `sys_pwrite()` to the Managarm sysdeps.
Blocked on managarm/managarm#430
=> options/posix: Implement pwrite

options/glibc/generic/resolv-stubs.cpp, options/glibc/include/resolv.h
This PR stubs `res_nclose()` and `res_ninit()`. As far as I'm aware, we can safely leave them as no-ops for now.
=> options/glibc: Stub res_nclose and res_ninit

options/ansi/generic/file-io.cpp, options/ansi/include/mlibc/file-io.hpp, options/ansi/include/stdio.h, tests/ansi/ungetc.c, tests/meson.build
This, together with a locking patch in gtk+3 (or a change in the way we lock things in file-io.cpp), allows gtk+3 to run again on Managarm. Many thanks to @64 for the test and fixing ungetc even further.
=> options/ansi: Handle EOF in ungetc properly

options/ansi/generic/string-stubs.cpp, options/ansi/include/string.h, options/posix/generic/posix_string.cpp, options/posix/include/bits/posix/posix_string.h, tests/meson.build, tests/posix/string.c
`stpcpy` previously lived in `options/ansi`.
=> options/posix: implement stpncpy and move stpcpy to posix

options/ansi/generic/time-stubs.cpp, tests/ansi/timegm.c, tests/meson.build
This PR implements `timegm()` as implemented by Sortix.
=> options/ansi: Implement timegm

options/posix/include/termios.h
This should fix `tcl` not building on Managarm ci.
=> options/posix: Define TIOCM_DTR and TIOCM_RTS

meson.build
Forgot this in #507. I guess nothing in the CI includes this header :^)
=> meson: install bits/inline-definitions.h

options/ansi/generic/file-io.cpp
This is the wrong way around since `__buffer_ptr >= __unget_ptr` holds as an invariant.
=> options/ansi: fix wrong pointer subtract in fread

options/rtdl/generic/linker.cpp
(detected by netbsduser while working on SCAL-UX)
With an rpath of "/", rtdl would fail to substring the rpath, causing an
assertion failure and hence a crash. As the code here implements a
replace functionality, such a substring failure should simply not do a
replace instead.
Depends on https://github.com/managarm/frigg/pull/33 (re-run checks when that gets merged)
=> rtdl: fix rpaths under 7 characters crashing rtdl

options/ansi/generic/stdlib-stubs.cpp, options/ansi/generic/string-stubs.cpp, options/internal/include/mlibc/strtol.hpp, options/posix/generic/lookup.cpp, tests/ansi/strtol.c
This PR fixes the current implementation of `strtol` and friends by replacing it with a generic implementation in idiomatic C++. It also adds a much more comprehensive set of tests.
When testing it was discovered that this commit somehow triggers an issue in `read_dns_name`, so we also fix that.
Fixes https://github.com/managarm/mlibc/issues/467.
=> options/ansi: fix strtol et al., implement wcstol et al.

ABI_BREAKS.md
Future PRs against the `abi-break` branch should add a note here explaining the change to downstream users.
=> meta: add ABI_BREAKS.md

.github/workflows/ci.yml, ci/bootstrap.yml, meson.build, options/internal/generic/essential.cpp, options/internal/generic/ubsan.cpp, options/rtdl/generic/main.cpp, tests/glibc/ffsl-ffsll.c, tests/meson.build
The `ffsl-ffsll` test had to also be fixed because it was crashing with UBSan enabled. We refactor it along the lines of #445.
=> options/internal: implement ubsan hooks for libc.so and ld.so internal usage

options/internal/riscv64/mlibc_crtend.S
This should fix the 'relocation truncated to fit' errors we see on the `abi-break` branch.
=> riscv: use far jump to init/fini

.github/workflows/ci.yml, ci/bootstrap.yml, meson.build, meson_options.txt, sysdeps/aero/meson.build, sysdeps/linux/meson.build, tests/meson.build
Fixes #514.
Tests for now only build against the shared libraries when `default_library=both`, but this could probably be fixed in a future PR (maybe once the big refactor of `tests/meson.build` in #460 is merged).
It does make the main meson.build slightly messier, but it's probably worthwhile (and I don't see an obvious way to rewrite it more cleanly).
=> meson: allow static and shared libs to be built simultaneously

options/internal/generic/inline-emitter.cpp, options/linux/include/sys/sysmacros.h
Also add `extern "C"` to the macros in `sys/sysmacros.h`
=> Fix inline-emitter not including mlibc-config.h

abis/linux/socket.h
=> abis/linux: Define SCM_CREDENTIALS

options/posix/include/unistd.h
=> options/posix: Define _SC_TTY_NAME_MAX

options/posix/include/sys/types.h
=> options/posix: Define more legacy types in use by acl

sysdeps/aero/generic/entry.cpp, sysdeps/dripos/generic/entry.cpp, sysdeps/ironclad/generic/entry.cpp, sysdeps/lemon/generic/entry.cpp, sysdeps/managarm/generic/entry.cpp, sysdeps/qword/generic/entry.cpp
This should reduce some confusion for new ports.
=> sysdeps: add reminder to call __dlapi_enter for static builds to work properly

tests/glibc/getopt.c
Should fix some recent build failures under UBSan.
=> tests/posix: fix getopt array access out of bounds

abis/linux/limits.h
=> abis/linux: Define LOGIN_NAME_MAX

abis/linux/signal.h, options/ansi/include/signal.h
=> abis/linux: Define _NSIG

options/posix/include/sys/types.h
=> options/posix: Define quad_t and u_quad_t

abis/linux/packet.h, abis/mlibc/packet.h, options/linux/include/netpacket/packet.h, sysdeps/aero/include/abi-bits/packet.h, sysdeps/aero/meson.build, sysdeps/dripos/include/abi-bits/packet.h, sysdeps/dripos/meson.build, sysdeps/ironclad/include/abi-bits/packet.h, sysdeps/ironclad/meson.build, sysdeps/lemon/include/abi-bits/packet.h, sysdeps/lemon/meson.build, sysdeps/linux/include/abi-bits/packet.h, sysdeps/linux/meson.build, sysdeps/managarm/include/abi-bits/packet.h, sysdeps/managarm/meson.build, sysdeps/qword/include/abi-bits/packet.h, sysdeps/qword/meson.build
This PR adds a bunch of missing constants into the Linux ABI. It also stubs 2 functions and adds 2 new sysdeps.
=> abis: Define PACKET_HOST

sysdeps/linux/include/bits/syscall.h
After #525, this macro was still missing. Add it to satisfy certain programs. Split from #564.
Part of mlibc LFS project.
=> sysdeps/linux: Add missing __syscall0 macro

options/ansi/generic/stdlib-stubs.cpp
=> options/ansi: cache value of env var MLIBC_DEBUG_MALLOC

tests/ansi/fopen.c
This was fixed earlier, but it doesn't hurt to add a test for this case. See #12.
=> tests/ansi: check that fclose(stdout) doesn't crash on exit

options/glibc/generic/getopt-stubs.cpp, tests/glibc/getopt.c
This currently prevent managarm from booting.
=> options/glibc: make getopt_long handle + in optstring

options/rtdl/generic/linker.cpp, options/rtdl/generic/linker.hpp, tests/rtdl/dl_iterate_phdr/test.c, tests/rtdl/meson.build, tests/rtdl/soname/libbar.c, tests/rtdl/soname/libfoo.c, tests/rtdl/soname/meson.build, tests/rtdl/soname/test.c
Fixes #585. Also fixes some hardcoding of paths in the `dl_iterate_phdr` test.
=> rtdl: don't load the same SONAME twice

options/internal/riscv64-include/mlibc/thread.hpp, options/rtdl/generic/linker.cpp, tests/posix/pthread_thread_local.c
Previously, the TCB was not correctly aligned:
* On AArch64 and RISC-V, the assumption `tp + sizeoc(Tcb) == tlsData` would break if sizeof(Tcb) was not a multiple of `tlsMaxAlignment`. This meant that adding members to `Tcb` would cause a breakage.
* On x86_64, we relied on the default alignment of the memory allocator to provide sufficient alignment for the TCB and TLS data (though this caused no breakage in practice).
This also fixes a bug whereby the `.tbss` was not being zeroed on the main thread.
=> rtdl: zero .tbss and correctly align TCB

options/rtdl/generic/main.cpp
=> options/rtdl: Initialize the debug state before initializing objects

options/ansi/include/limits.h, options/internal/include/mlibc/tcb.hpp, options/posix/generic/pthread-stubs.cpp, options/posix/include/pthread.h, options/rtdl/generic/linker.cpp, sysdeps/linux/riscv64/cp_syscall.S, tests/posix/pthread_key.c
Followed on from #618. This avoids a call to `__tls_get_addr` inside `pthread_getspecific` / `pthread_setspecific`, which should allow ASan to function. We also add some locking that was missed before.
~~Blocked on #622.~~
=> options/posix: move local pthread keys into TCB

ABI_BREAKS.md, abis/dripos/errno.h, options/ansi/generic/stdio-stubs.cpp, options/internal/aarch64-include/mlibc/thread.hpp, options/internal/include/mlibc/tcb.hpp, options/internal/riscv64-include/mlibc/thread.hpp, options/internal/x86_64-include/mlibc/thread.hpp, options/posix/generic/pthread-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, options/posix/include/pthread.h, sysdeps/aero/generic/aero.cpp, sysdeps/aero/generic/thread.cpp, sysdeps/aero/include/mlibc/thread-entry.hpp, sysdeps/dripos/generic/generic.cpp, sysdeps/dripos/generic/thread.cpp, sysdeps/lemon/generic/lemon.cpp, sysdeps/lemon/generic/thread.cpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/linux/generic/thread.cpp, sysdeps/linux/riscv64/cp_syscall.S, sysdeps/managarm/aarch64/thread.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/managarm/x86_64/thread.cpp, tests/ansi/sscanf.c, tests/meson.build, tests/posix/pthread_attr.c
=> All pthread_attr_* support

options/ansi/musl-generic-math/weak_alias.h
`libsanitizers` was complaining about `signgam`, and while we did what musl does, this seems to please `libsanitizers`.
=> options/ansi: Fix signgam declaration

sysdeps/linux/include/sys/syscall.h
I got compilation failures if this header is not included, I'm unsure about whether this is correct, so feedback is appreciated.
=> sysdeps/linux: Include unistd.h in sys/syscall.h

options/glibc/include/net/if_ppp.h, options/glibc/include/net/route.h, options/glibc/include/netax25/ax25.h, options/glibc/include/netipx/ipx.h, options/glibc/include/netrom/netrom.h, options/glibc/meson.build
`libsanitizers` makes use of these headers, and glibc provides them.
=> options/glibc: Add some more network headers

options/posix/generic/dlfcn-stubs.cpp, options/posix/include/dlfcn.h
The implementation is only partial, as the version argument is ignored. Thus, `dlvsym` behaves just like `dlsym`.
=> options/posix: Add dlvsym

ABI_BREAKS.md, abis/linux/termios.h, abis/linux/wait.h, abis/mlibc/signal.h, abis/mlibc/termios.h, abis/mlibc/utsname.h, abis/mlibc/wait.h, meson.build, sysdeps/aero/include/abi-bits/signal.h, sysdeps/aero/include/abi-bits/termios.h, sysdeps/aero/include/abi-bits/utsname.h, sysdeps/aero/include/abi-bits/wait.h, sysdeps/managarm/include/abi-bits/signal.h, sysdeps/managarm/include/abi-bits/utsname.h, sysdeps/managarm/include/abi-bits/wait.h
As discussed on Discord. This deprecates some headers in the `mlibc` ABI in favour of the Linux ABI. This partially reverts #580 (a deprecation notice is added instead).
Once we are happy with this PR, we should ping all the sysdep owners to see if they are happy to have their sysdeps moved over to the Linux ABI too, because these changes will require some modifications to their kernels.
Fixes #430, fixes #257, fixes #466.
=> abis: deprecate some headers in the mlibc ABI

options/glibc/include/sys/mtio.h, options/glibc/include/sys/personality.h, options/glibc/include/sys/timeb.h, options/glibc/meson.build
This PR includes some headers that seem to be glibc extensions and are located in `sys/`. Two of those just need to exist for now, this pleases `libsanitizers`.
=> options/glibc: Add more missing headers

options/posix/include/dirent.h, options/posix/include/sys/syslog.h, options/posix/meson.build
Round 3, mostly defines again, a few structs, two missing headers and several compatibility defines.
=> Various fixes for mlibc LFS part 3

meson.build, options/ansi/generic/stdlib-stubs.cpp, options/internal/generic/global-config.cpp, options/internal/include/mlibc/global-config.hpp, options/posix/generic/posix_stdlib.cpp, options/rtdl/generic/main.cpp, options/rtdl/include/mlibc/rtdl-config.hpp
This PR adds a mechanism to pass global program configuration data between `ld.so` and `libc.so`, laying the groundwork for #614.
=> options/{internal,rtdl}: add GlobalConfig and RtdlConfig

sysdeps/managarm/generic/file.cpp
As discussed on Discord, this change is to make `uname -s` print `Managarm` instead of `managarm`.
=> sysdeps/managarm: managarm should be Managarm in sys_uname

abis/linux/limits.h, abis/mlibc/limits.h
Xorg libraries really liked `OPEN_MAX`, so I defined it. `libsanitizers` was complaining about `struct termio`, but it seems obsolete. I added it to the linux abi as to not pollute the global headers.
=> abis/linux: Add some missing defines

options/rtdl/generic/linker.cpp
A memory deallocation bug was found and fixed in rtdl.
Found with the assistance of https://github.com/managarm/mlibc/pull/682 (thanks qookie).
=> options/rtdl: Fix a memory deallocation bug in accessDtv

sysdeps/linux/generic/sysdeps.cpp
Due to #677, the openat sysdep in linux was wrong. Fix this.
=> sysdeps/linux: Fix the signature for sys_openat

options/ansi/generic/wchar-stubs.cpp
An out of bounds read was found and fixed while running with the debug allocator.
Found with the assistance of #682 (thanks qookie).
=> options/ansi: Fix out of bounds read in wcswidth

abis/linux/auxv.h
Some additional values for auxv.
=> abis/linux: Define additional AT_ values

options/rtdl/generic/main.cpp, tests/rtdl/dl_iterate_phdr/test.c
This matches the behavior of glibc and pleases ASan.
Fixes #579
=> options/rtdl: Ignore the first item in __dlapi_iterate_phdr

options/glibc/include/resolv.h
=> options/glibc: Add more members to struct res_state

internal-config.h.in, meson.build, meson_options.txt, options/internal/generic/allocator.cpp, options/internal/include/mlibc/allocator.hpp
This allocator uses mmap for every allocation, performs explicit checks
on the given arguments, adds a guard page after every allocation (while
placing the allocation as close to it as possible), and, if configured
to do so, will never release virtual addresses to catch a certain
category of use-after-free bugs.
=> options/internal: add a more strict debug allocator

abis/linux/signal.h
=> abis/linux: Define some siginfo constants

abis/linux/stat.h
=> abis/linux: Define S_IEXEC

abis/linux/blkcnt_t.h, abis/linux/blksize_t.h, abis/linux/dev_t.h, abis/linux/fsfilcnt_t.h, abis/linux/ino_t.h
Verified against musl, see https://github.com/bminor/musl/blob/46d1c7801bb509e1097e8fadbaf359367fa4ef0b/include/alltypes.h.in#L27-L35.
=> abis/linux: correct the ABI of some integer types

ABI_BREAKS.md, options/posix/include/sys/socket.h
```
Excerpt from sys/socket.h:
// Control message format:
// The offsets marked with ^ are aligned to alignof(size_t).
//
// |---HEADER---|---DATA---|---PADDING---|---HEADER---|...
// ^            ^                        ^
// |---------CMSG_LEN------|
// |---------------CMSG_SPACE------------|
By this definition, control message header and data should both be
aligned to (at least) alignof(size_t), however, previously, the
implementation of these macros in options/posix relied on
sizeof(struct cmsghdr) % sizeof(size_t) being zero. After the recent
change to socklen_t, this no longer held true, and DATA would be aligned
to a 12 byte boundary (on x86_64), and hence would move all data back a
bit. Code that relied on CMSG_ALIGN() to compute sizes of cmsg data
(notably, sysdeps/managarm) …
```
=> sys/socket.h: fix some CMSG_ macros not aligning

options/posix/include/sched.h, options/posix/include/ucontext.h
These are currently wrong, and their meaning changes in the near future, which prompted me to search for them
=> *: replace instances of () with (void) in C headers

options/posix/generic/posix_stdlib.cpp
The new glib update seems to like strtod_l, so let's make it a call to strtod as to not break 75% of Managarm userspace.
=> options/posix: Make strtod_l call strtod

options/internal/include/mlibc/internal-sysdeps.hpp, options/rtdl/generic/linker.cpp
In the name of security.
Tested on Ironclad and Lyre, where it worked, I would appreciate if someone tried it on linux or managarm for completeness
=> rtdl: Use mprotect to remove superfluous permissions

sysdeps/managarm/generic/file.cpp
This PR adds missing error handling to `sys_msg_send` and `sys_fallocate` in the Managarm sysdeps.
=> sysdeps/managarm: Add missing error handling

internal-config.h.in, meson.build, options/rtdl/generic/linker.cpp
This gives us library ASLR for free, and means we don't try mapping libraries over anything else that exists in the address space at our arbitrarily chosen base addresses. Enabled for Linux currently.
Also enabled MAP_DSO_SEGMENTS for Linux, as that seemed appropriate.
=> options/rtdl: add support for allocating DSO address space with mmap

sysdeps/managarm/generic/file.cpp
This PR stubs two sysdeps that are regularly called and seem to prevent `xbps` from working with ENOSYS errors. I must note that this doesn't fix the entirety of `xbps` on Managarm.
=> sysdeps/managarm: Stub two sysdeps

abis/linux/in.h
=> abis/linux: Add various missing ip related structs and defines

options/posix/generic/sys-mman-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/managarm/generic/file.cpp
While working on more webkit memes, we found that webkit likes mlock to not crash, so I made that a sysdep. I've also improved the error handling for `sys_symlinkat` in the Managarm sysdeps.
=> Add mlock sysdeps + sys_symlinkat error code fixes

abis/linux/signal.h
This breaks wine, probably among other things.
=> abis/linux: Fix wrong member name in mcontext_t

options/glibc/generic/shadow-stubs.cpp, options/glibc/include/shadow.h, options/linux/generic/utmp-stubs.cpp, options/linux/include/utmp.h, options/posix/generic/unistd-stubs.cpp, options/posix/include/unistd.h
This PR implements `getspnam()` and `getspnam_r`, fixes the function signature of `setpgrp` to match the System V version, just like glibc and musl do, adds a stub `fgetspent` and stubs `sys_tcdrain` in Managarm. All of this works towards running the `shadow` package on Managarm.
As more work is expected, this is a draft for now.
=> More work towards shadow support

sysdeps/lyre/generic/generic.cpp, sysdeps/vinix/generic/generic.cpp
This PR fixes an issue on both the Vinix and Lyre sysdeps where sys_poll() never waits indefinitely when a negative integer is passed to it.
=> Sysdep fixes for Vinix and Lyre

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/ioctl.cpp
A small fix that eliminates `glxgears` crashing when closing the program.
=> sysdeps/managarm: Handle ENOTCONN for FIONREAD ioctl

options/ansi/generic/stdio-stubs.cpp, options/ansi/generic/string-stubs.cpp, options/ansi/generic/time-stubs.cpp, options/internal/generic/locale.cpp, options/linux/generic/mntent-stubs.cpp, tests/ansi/strftime.c, tests/posix/posix_spawn.c
While working on `claws`, we hit a few problems which I fixed. This PR includes an implementation of `fgets_unlocked`, `strxfrm`, a bunch of the `mntent` family of functions and two missing `strftime` specifiers. I also included tests for the missing specifiers and fixed a failing posix_spawn test under debian (no, not everyone has `/bin` symlinked to `/usr/bin`, debian unstable apparently doesn't).
=> Several fixes for claws to work

abis/linux/signal.h, options/glibc/include/resolv.h
We found some missing items for Chromium while @czapek1337 was building chromium under cbuildrt. This includes some missing signal constants in the Linux ABI. This PR fixes them.
=> Some small things for Chromium

sysdeps/managarm/generic/drm.cpp, sysdeps/managarm/generic/ioctl.cpp
Split off from #812. This is the mlibc part of managarm/managarm#519.
=> sysdeps/managarm: rework ioctls to allow using dedicated messages

meson.build, options/internal/include/bits/cpu_set.h, options/linux/generic/cpuset.cpp, options/linux/generic/sched.cpp, options/linux/include/bits/linux/cpu_set.h, options/linux/include/bits/linux/linux_sched.h, options/linux/include/mlibc/linux-sysdeps.hpp, options/linux/meson.build, options/posix/generic/pthread-stubs.cpp, options/posix/generic/sched-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, options/posix/include/pthread.h, options/posix/include/sched.h, tests/linux/cpuset.c, tests/linux/pthread_attr.c, tests/meson.build, tests/posix/pthread_attr.c
=> `CPU_*` macros

options/posix/generic/posix_locale.cpp
This spams a lot during `WebKitGTK` operations, and that eats performance in QEMU. This _should_ only log it once now.
=> options/posix: Limit the logging of newlocale and uselocale

options/ansi/generic/stdio-stubs.cpp, options/ansi/include/stdio.h, options/ansi/include/wchar.h, options/internal/include/bits/null.h, options/internal/include/bits/size_t.h, options/internal/include/bits/wchar_t.h, options/internal/include/bits/wint_t.h, options/posix/generic/posix_stdio.cpp, options/posix/include/bits/posix/posix_stdio.h
This PR makes it so mlibc does not make assumptions about magic modifier macros to change the behaviour of *non* mlibc-provided freestanding headers.
=> misc: Do not rely on magic macros to modify freestanding header behaviour

options/posix/generic/sched-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp
This adds support for the `sched_get_priority_max()` function if the appropriate sysdep is available.
=> options/posix: Support sched_get_priority_max()

options/ansi/generic/stdlib-stubs.cpp, tests/ansi/calloc.c, tests/meson.build
=> options/ansi: prevent multiplication overflows in calloc

options/ansi/include/mlibc/ansi-sysdeps.hpp, options/internal/generic/threads.cpp, sysdeps/aero/generic/thread.cpp, sysdeps/dripos/generic/thread.cpp, sysdeps/keyronex/generic/thread.cpp, sysdeps/lemon/generic/thread.cpp, sysdeps/linux/generic/thread.cpp, sysdeps/lyre/generic/thread.cpp, sysdeps/managarm/aarch64/thread.cpp, sysdeps/managarm/x86_64/thread.cpp, tests/posix/pthread_attr.c
Change sp assignment in sys_prepare_stack in case `*stack` is not null to `*stack + *stack_size`, because *stack points to the bottom of the stack and not top. As it is currently the writes later down in this function would be out of bounds in that case.
=> sysdeps: Fix sp assignment in sys_prepare_stack

sysdeps/managarm/generic/file.cpp
Node.js is using O_CLOEXEC, and on Linux that's the same, but on Managarm it is not.
=> sysdeps/managarm: Make epoll_create accept O_CLOEXEC too

options/rtdl/generic/linker.cpp
Previously, we didn't assert this at least on some architectures, including x86_64. This apparently breaks `libmbus.so`.
=> options/rtdl: return previous behavior of not ensuring symbol resolution

abis/linux/errno.h, abis/mlibc/errno.h, sysdeps/managarm/generic/file.cpp
Fix a bug where if a file is crated with open or openat, it will not have any permission modes.
More importantly, this removes about 50% of log spam.
Managarm PR: [managarm#568](https://github.com/managarm/managarm/pull/568l)
=> managarm: send mode in openat to posix

sysdeps/managarm/generic/socket.cpp
Firefox uses them, stub them for now.
=> sysdeps/managarm: Stub two setsockopt calls

sysdeps/managarm/generic/file.cpp
Forgot to include this in the abi switch, my bad.
=> sysdeps/managarm: Fix the type_mask and the flags_mask

sysdeps/managarm/generic/file.cpp
It's all static data for now, but it's better than the `???` everywhere.
=> sysdeps/managarm: Fill in more uname information

options/ansi/generic/assert-stubs.cpp, options/glibc/generic/glibc-assert.cpp
Atleast on clang [[noreturn]] is not the same as `__attribute__((__noreturn__))` used in the header and it fails to compile because of that.
=> Fix assert noreturn on clang

sysdeps/managarm/generic/time.cpp
helGetClock is a raw counter, so warning here makes no sense.
=> sysdeps/managarm: remove CLOCK_MONOTONIC_RAW warning

options/posix/generic/posix_signal.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/managarm/generic/signals.cpp
Managarm part depends on [managarm#601](https://github.com/managarm/managarm/pull/601).
=> posix, managarm: implement sigpending

abis/linux/signal.h
Should be merged before [bootstrap-managarm#284](https://github.com/managarm/bootstrap-managarm/pull/284)
=> abis/linux: correct type of sigset_t

options/ansi/generic/complex-stubs.c, options/ansi/meson.build
This fixes an issue where the 'complex' type is not defined for C++ sources
=> options/ansi: Move complex-stubs.cpp to complex-stubs.c

options/posix/generic/termios-stubs.cpp
=> termios-stub.cpp: make sure _GNU_SOURCE is defined

options/rtdl/generic/linker.cpp, tests/rtdl/meson.build, tests/rtdl/tls_align/libbar.c, tests/rtdl/tls_align/libfoo.c, tests/rtdl/tls_align/meson.build, tests/rtdl/tls_align/test.c
The alignment overhead is used to properly align the TCB, which on x86_64 needs to be aligned to the max TLS block alignment so that accessing blocks before it yields aligned addresses.
Fixes #960.
=> options/rtdl: Fix alignment overhead computation for the TLS allocation

meson.build
I've had issues building a host-mlibc and I fixed it by providing cxxshim and I needed this patch for cxxshim headers to be used.
=> meson: Don't use libstdc++ headers if cxxshim is available

sysdeps/managarm/generic/entry.cpp, sysdeps/managarm/x86_64/crt-src/Scrt1.S, sysdeps/managarm/x86_64/crt-src/crt0.S
This causes an ABI break, needed for upcoming gobject-introspection stuff
=> sysdeps/managarm: Add missing call to __dlapi_enter

options/posix/generic/pthread-stubs.cpp, options/posix/include/pthread.h
It's currently returning an int, and spec says it should be noreturn void. Draft as I'm not quite sure if this is now correct.
=> options/posix: Fix function prototype of pthread_exit

sysdeps/managarm/aarch64/crt-src/Scrt1.S, sysdeps/managarm/aarch64/crt-src/crt0.S
The entry point was changed to include the sp parameter but the AArch64 crts weren't updated.
=> sysdeps/managarm: Fix AArch64 crt

sysdeps/linux/x86/crt-src/crti.S, sysdeps/linux/x86/crt-src/crtn.S
Mark stack in crti and crtn of linux sysdep non-executable.
This also makes the behavior consistent with other crt files.
=> Add .note.GNU-stack to crt files of linux x86 sysdep

meson.build
In some cases the rtdl can contain unwanted relocations to symbols from c++ stdlib when built in debug mode, this can be fixed by using `-fvisibility-inlines-hidden` in addition to `-fvisibility=hidden`.
=> rtdl: Fix debug mode build

options/glibc/include/bits/glibc/glibc_icmp6.h, options/glibc/meson.build, options/posix/include/netinet/icmp6.h
Currently if the glibc option is enabled it overwrites the posix icmp6.h header with the extension header.
=> options/glibc: Don't overwrite posix icmp6.h

options/posix/include/mlibc/posix-sysdeps.hpp
`posix-sysdeps.hpp` currently declares `sys_times` as `int sys_times(struct tms *, clock_t*)`.
However, if `sys/times.h` was not included **before** `posix-sysdeps.hpp`, in which `struct tms` is declared, 
the `struct tms` is instead implicitly declared in the parameter list, thus making implementing `sys_times` very problematic, if not impossible.
This PR fixes the bug by adding the include to `posix-sysdeps.hpp`.
=> Add sys/times.h include to posix-sysdeps.hpp

tests/meson.build, tests/rtdl/ld_library_path/meson.build, tests/rtdl/meson.build, tests/rtdl/preinit/meson.build, tests/rtdl/rtld_next/meson.build
When only using link_with it doesn't look to be properly taking transitive dependencies into account leading into issues when using the headers that cshim provides.
=> tests: Fix include paths when using cshim

options/rtdl/generic/linker.cpp
I forgot to update this case in the dl non-elf pr.
=> options/rtdl: Return LinkerError instead of nullptr on error

options/ansi/generic/file-io.cpp, options/posix/generic/posix-file-io.cpp, options/posix/generic/posix_stdio.cpp, options/posix/include/mlibc/posix-file-io.hpp, tests/meson.build, tests/posix/fmemopen.c
=> Implement `fmemopen`

options/posix/generic/dlfcn-stubs.cpp, options/posix/include/dlfcn.h, options/rtdl/generic/main.cpp, tests/meson.build
This is also a gnu extension so I am not sure if it should be guarded behind _GNU_SOURCE or __MLIBC_GLIBC_OPTION but it doesn't look like the existing `dladdr` is guarded either.
=> options/posix: Implement dladdr1

options/glibc/include/paths.h, options/linux/generic/utmpx.cpp, options/linux/include/utmpx.h
options/linux: Define more utmpx stuff
=> options/glibc: Add utmpx paths

options/internal/include/mlibc/tcb.hpp, options/rtdl/generic/linker.cpp, options/rtdl/x86_64/runtime.S
I am not sure if the dynamic tlsdesc assembly is right at all, so someone should check it.
=> options/rtdl: Implement tlsdesc for x86_64

internal-config.h.in, meson.build, meson_options.txt, options/rtdl/generic/linker.cpp, options/rtdl/generic/main.cpp
One scenario where overriding the default search paths is useful is when mlibc is used as a 'secondary' libc on a system. Absent this patch, mlibc will look for libraries in `/lib` and `/usr/lib`, but we want it to look in `/some/mlibc/sysroot/lib` instead.
Note that this is only needed if dynamic linking is used. To my knowledge, `musl` and `glibc` do not support a similar feature, requiring local patching instead.
=> rtdl: make default library search paths configurable at build time

options/posix/include/fcntl.h, options/posix/include/netdb.h
The AT_STATX one is for glib, the NI_IDN one is for InitWare
=> Add two missing defines

abis/linux/statx.h
Fix incorrectly named `stx_dio_offset_align` in `statx` struct.
=> abis/linux: fix stx_dio_offset_align name in statx

options/linux/meson.build
Add missing `sys-statx.cpp` source to `options/linux/meson.build`
=> options/linux: add sys-statx.cpp to sources

options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/managarm/generic/file.cpp
This PR contains a bugfix for Managarm's `sys_openat()` sysdep, and it fixes the function signature for `sys_mkfifoat()`. The signature change has no impact on users of the mlibc ABI, as `mode_t` is an `int` there, but for users of the Linux ABI it matters as `mode_t` is `unsigned int`.
=> Some small fixes found during elogind debugging

options/rtld/generic/linker.cpp, sysdeps/managarm/rtld-generic/support.cpp
Store the tls offset relative to the end of the tcb instead of the start of the tp in the tlsAboveTp case and take into account possible padding between the tls space and the tp in relocations.
=> options/rtdl: Fix tls in tlsAboveTp case

options/internal/include/mlibc/file-window.hpp
Use provided `path` parameter, instead of hardcoded `/etc/localtime` in constructor of `file_window`.
=> options/internal: use provided path in file_window

abis/linux/stat.h, sysdeps/linux/generic/sysdeps.cpp
Set `st_atim`, `st_mtim` and `st_ctim` based on internal (`__st_xxx32`) fields.
=> x86: Correctly set time fields in stat on Linux

abis/linux/stat.h
First defined: https://github.com/managarm/mlibc/blob/266ec427d78fa3deae7c288aaffc3709dbdb2903/abis/linux/stat.h#L29
Redefined in the same file but a few lines below: https://github.com/managarm/mlibc/blob/266ec427d78fa3deae7c288aaffc3709dbdb2903/abis/linux/stat.h#L44
=> fix(abis/linux): remove redefinition of `S_IEXEC`

options/ansi/generic/stdio-stubs.cpp, tests/ansi/sscanf.c
Fix the do_scanf function not returning EOF when it can't read any more, as well as missing matching error handling in a few places.
=> options/ansi: better do_scanf EOF and matching error handling 

options/posix/generic/posix_stdlib.cpp, options/posix/include/bits/posix/posix_stdlib.h
=> options/posix: Stub getsubopt

sysdeps/managarm/generic/file.cpp
Depends on [managarm#671](https://github.com/managarm/managarm/pull/671)
=> sysdeps/managarm: handle directoryNotEmpty error from rmdir

options/posix/generic/posix_stdlib.cpp, options/posix/include/bits/posix/posix_stdlib.h, scripts/rust-libc.py
Needed for `perl`, borrowed by @no92 from musl.
=> options/posix: Implement erand48, drand48, seed48 and srand48

options/posix/generic/unistd-stubs.cpp
Handle ``_SC_LOGIN_NAME_MAX`` in the default ``sysconf()`` switch. Some programs such as ``login`` need this.
=> options/posix: handle _SC_LOGIN_NAME_MAX in sysconf

options/posix/generic/unistd-stubs.cpp
Setting argv[0] is broken in execle() as its sets the first pointer in the array to itself instead of the arg0 passed to the function.
=> options/posix: fix execle() argv[0]

options/ansi/generic/time-stubs.cpp, options/internal/generic/locale.cpp, tests/ansi/strftime.c
This PR fixes 2 bugs and implements 5 new modifiers for strftime.
These were all found while running the testsuite from glib.
=> options/ansi: Various fixes to strftime

sysdeps/managarm/generic/ensure.cpp
Needs to be merged along with managarm/managarm#690.
=> sysdeps/managarm: pass a severity parameter to helLog

abis/linux/in.h, options/ansi/include/inttypes.h, options/posix/generic/posix_stdio.cpp, options/posix/generic/posix_string.cpp, options/posix/include/bits/posix/posix_stdio.h, options/posix/include/bits/posix/posix_string.h, sysdeps/managarm/generic/socket.cpp
Notably, this misses an implementation for `tdelete` and `twalk`, which are used for even the simplest things like `vlc --help`.
=> Several additions for VLC

options/ansi/generic/stdio-stubs.cpp, options/internal/include/mlibc/strtol.hpp, tests/ansi/sprintf.c, tests/ansi/sscanf.c, tests/ansi/strtol.c
Support C23 binary printf/scanf/strtol specifiers. Depends on https://github.com/managarm/frigg/pull/72 and closes https://github.com/managarm/mlibc/issues/1103.
=> options/ansi: Handle binary specifiers in format strings

options/posix/generic/unistd-stubs.cpp, tests/meson.build, tests/posix/usershell.c
Needed for ``su -``. Used the pwd code as a reference.
=> options/posix: implement {get,set,end}usershell

options/posix/generic/grp-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/ironclad/generic/generic.cpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/lyre/generic/generic.cpp, sysdeps/vinix/generic/generic.cpp, tests/posix/grp.c
``sys_getgroup`` should take a ``gid_t *`` instead of a ``const gid_t *``, as it is expected to write there.
Implement ``putgrent``, needed by ``useradd`` to create the user group when creating a user.
=> options/posix: change sys_getgroup parameters and implement putgrent

options/ansi/include/limits.h
Compiling MPFR yielded the following messages:
```
/host/usr/include/limits.h:76:31: warning: integer overflow in expression of type 'int' results in '-2' [-Woverflow]
76 | #define UINT_MAX (__INT_MAX__ * 2 + 1)
../../mpfr-src/src/invert_limb.h:136:7: note: in expansion of macro 'MPFR_STAT_STATIC_ASSERT'
136 |       MPFR_STAT_STATIC_ASSERT (4182025 <= UINT_MAX);   
```
After some time looking through at possible fixes, I have discovered that UINT_MAX is evaluated to be a signed integer
rather than an unsigned one in ansi/include/limits.h, this can be fixed by adding 2 U's.
=> fix: options/ansi make UINT_MAX unsigned

meson.build, scripts/hide-everything.ld
result: https://gist.github.com/ArsenArsen/570e87410c48f5b17f46d579269f10c2
btw, I noticed that we have a C++ function that probably should not be a C++ function:
```
0000000000068a58 T seed48(unsigned short*)
000000000008354a T login_tty(int)
000000000009f478 T wcstoimax(wchar_t const*, wchar_t**, int)
000000000009f4b7 T wcstoumax(wchar_t const*, wchar_t**, int)
```
this would imply we lack tests for those..
I recall some discussion about how to detect such cases before in the mlibc channel, but I do not recall the result.  if you can find it/remember it, please share
=> meson: hide all libc.so C++ symbols via a linker script

options/ansi/include/inttypes.h, options/linux/generic/pty-stubs.cpp, options/linux/include/utmp.h, options/posix/include/bits/posix/posix_stdlib.h
As discovered by #1119, some functions were erroneously mangled, which was caused by missing/broken prototypes in headers.
=> Fix functions that were mangled by accident

options/internal/gcc-extra/cxxabi.cpp, options/rtld/generic/main.cpp
These changes are needed to make mlibc compile for managarm, with clang. The result seems to work fine as a drop-in replacement for a gcc-compiled one.
=> Compilation with clang for managarm

options/internal/aarch64/setjmp.S
The __mlibc_jmpbuf_register_state struct is good,
but the saving/restoring it was not.
As such, no ABI break.
=> options/internal: correct setjmp/longjmp on aarch64

options/internal/gcc/guard-abi.cpp
Compilers targeting the Motorola 68k generally align on a 2-byte boundary, so the guard is laid out wrongly and becomes a 6-byte structure.
=> options/internal: add padding to Guard

options/posix/include/bits/posix/posix_signal.h
They appear to be from glibc's sys/ucontext.h, which only defines them under that condition.
=> options/posix: guard some fpu state definitions behind __x86_64__

options/internal/generic/sigset.cpp
This makes the `sigset_t` manipulation functions work on big-endian targets.
=> options/internal: endian-agnostic sigset_t functions

options/ansi/musl-generic-math/__fpclassifyl.c, options/ansi/musl-generic-math/libm.h
Borrowed from https://github.com/kraj/musl/commit/18f02c42a2b5397e8541f4663eb6ca00c1a806dd
=> options/internal: fix 80-bit long doubles on big endian arches

options/posix/generic/posix_stdlib.cpp, tests/posix/realpath.c
The old absolute symlink handling code unconditionally ignored one character from the end of the path returned by readlink, which broke realpath on any absolute links without a trailing slash. (discovered when a ``header.h`` path became ``header.`` while compiling GCC)
This new code will ignore all trailing slashes instead.
=> options/posix: fix realpath(3) absolute symlink handling

options/internal/gcc/initfini.cpp, options/lsb/generic/dso_exit.cpp, options/rtld/generic/linker.cpp, options/rtld/generic/linker.hpp, options/rtld/generic/main.cpp, tests/rtld/destroy/test.c, tests/rtld/meson.build
This is needed to support functions marked with attribute gnu::destructor. ~The way I implemented it it destructs the objects in reverse order that they were initialized in and first runs functions registered with __cxa_atexit for the object and after that the fini functions for that object, I am not sure if that's completely correct but to me it seems reasonable enough so in case of an object that doesn't have any circular dependencies both the atexit functions and destructor functions are run after the object can't be used by anything anymore.~ It turned out that there is an autogenerated call to __cxa_finalize that should call the functions registered for that dso, so I implemented that.
=> options/rtld: Call fini functions on exit

options/internal/include/mlibc/lock.hpp
On m68k the default alignment of 2 bytes for a uint32_t may result in futex calls failing under some conditions, as a futex must be 4-byte aligned.
=> options/internal: ensure FutexLockImpl alignment to 4 bytes

tests/posix/pthread_attr.c
It was previously writing to what was likely the current stack pointer, but should have been writing to the start of the alloca()'d area.
=> tests/pthread_attr: fix trampling of the stack

options/internal/gcc/initfini.cpp, options/lsb/generic/dso_exit.cpp, options/rtld/generic/linker.cpp, options/rtld/generic/linker.hpp, options/rtld/generic/main.cpp, tests/rtld/destroy/test.c, tests/rtld/meson.build
PR #1092 may have been prematurely merged as it causes issues with certain programs as reported by the Astral project. Revert it for now.
=> Revert "options/rtld: Call fini functions on exit"

mlibc-config.h.in
This was not removed by 6dff15d7ca0aa40f15b66da7465e0cf4042a64d6 so do that now. Further addresses #1150
=> misc: Remove C99+ style comment from mlibc-config.h.in

options/rtld/generic/main.cpp
This breaks when mlibc is linked using -Wl,-z,pack-relative-relocs, remove the check.
=> rtld: remove check about ld.so having rel/rela relocations

options/rtld/generic/main.cpp
Fix build error caused by a semantic merge conflict.
=> options/rtld: fix semantic merge conflict

.github/workflows/abidiff.yml, .github/workflows/ci.yml, .github/workflows/detect-bad-ifs.yml, .github/workflows/detect-missing-mlibc-config.yml, .github/workflows/rust-libc.yml
Given we use a merge queue now, I don't see a reason to run checks on `push` anymore.
=> ci: don't run hooks on push

options/internal/include/bits/types.h
This commit correctly checks whether the C++ standard is new enough, and if so, uses the standard-defined `static_assert`. In the case of C, gcc and clang implement `_Static_assert` as an extension irrespective of the chosen C standard. Otherwise, we fall back to not checking the condition. We need to do the `extern int` hack in order to not produce errors in pedantic mode, as a single semicolon or `(void)0` at file scope give warnings or errors then.
This was originally discovered when compiling libstdc++, which uses `-std=gnu++98` and was throwing errors.
=> options/internal: fix static asserts for pre-C++03

options/ansi/include/inttypes.h
This is needed for tzdata 2024b
=> options/ansi: inttypes.h: Add SCNdFAST64 macro

options/rtld/generic/main.cpp
ld.so can contain an `DT_BIND_NOW` entry if mlibc is compiled with `-Wl,-z,now`.
=> rtld: Ignore DT_BIND_NOW for ld.so

sysdeps/managarm/generic/ioctl.cpp
Blocked on managarm/managarm#725.
=> sysdeps/managarm: better `EVIO*` ioctl handling

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/meson.build, sysdeps/managarm/riscv64/crt-src/Scrt1.S, sysdeps/managarm/riscv64/crt-src/crt0.S, sysdeps/managarm/riscv64/crt-src/crti.S, sysdeps/managarm/riscv64/crt-src/crtn.S, sysdeps/managarm/riscv64/thread.cpp
=> sysdeps/managarm: make RISC-V compile and link

sysdeps/linux/riscv64/crt-src/Scrt1.S, sysdeps/linux/riscv64/crt-src/crt1.S, sysdeps/managarm/riscv64/crt-src/Scrt1.S, sysdeps/managarm/riscv64/crt-src/crt0.S
This ensures that `gp` is properly set up even if it is used in `.init_array`.
=> sysdeps/{linux,managarm}: Set RISC-V gp from .preinit_array

.github/workflows/ci.yml, options/ansi/include/uchar.h, options/posix/include/fcntl.h
Previously only C ISO versions were checked. Check C++ versions too.
=> ci: check public headers conform to c++ ISO standards

options/elf/include/elf.h, options/internal/aarch64-include/mlibc/thread.hpp, options/internal/m68k-include/mlibc/thread.hpp, options/internal/riscv64-include/mlibc/thread.hpp, options/internal/x86-include/mlibc/thread.hpp, options/internal/x86_64-include/mlibc/thread.hpp, options/posix/generic/dlfcn.cpp, options/rtld/aarch64/elf.hpp, options/rtld/generic/linker.cpp, options/rtld/generic/linker.hpp, options/rtld/generic/main.cpp, options/rtld/m68k/elf.hpp, options/rtld/riscv64/elf.hpp, options/rtld/x86/elf.hpp, options/rtld/x86_64/elf.hpp, tests/meson.build, tests/rtld/meson.build, tests/rtld/symver/libfoo.c, tests/rtld/symver/libfoo.ver, tests/rtld/symver/meson.build, tests/rtld/symver/test.c
There's some minor TODOs left in the code (handling weak versions and figuring out what to do about VERDEF dependency names), but this is sufficient to fix #1208, and the TODOs aren't a problem when booting Managarm (which has plenty of libraries with versioned symbols).
Closes #1208.
=> Symbol versioning support

abis/linux/fcntl.h, abis/linux/ino_t.h
Part of the systemd on Linux project.
=> abis/linux: Add some defines needed for systemd

options/glibc/generic/shadow.cpp, options/glibc/include/shadow.h, options/glibc/include/sys/procfs.h
Part of the systemd on Linux project.
=> Various fixes and stubs to the glibc option for systemd

options/ansi/generic/locale.cpp, options/elf/generic/startup.cpp, options/elf/include/mlibc/elf/startup.h, sysdeps/aero/generic/entry.cpp, sysdeps/astral/generic/entry.cpp, sysdeps/dripos/generic/entry.cpp, sysdeps/ironclad/generic/entry.cpp, sysdeps/keyronex/generic/entry.cpp, sysdeps/lemon/generic/entry.cpp, sysdeps/linux/generic/entry.cpp, sysdeps/lyre/generic/entry.cpp, sysdeps/managarm/generic/entry.cpp, sysdeps/vinix/generic/entry.cpp
Move some initialisation tasks to gnu::constructor functions defined inside mlibc.
=> sysdeps: simplify entry point

meson.build
Building frigg's tests does not make sense in mlibc, it creates packaging issues (due to the dependency on gtest) and unnecessary stuff being done in CI (probably negligible, but frigg has it's own CI so we don't need to do that here)
=> build: Disable frigg's build_tests

options/lsb/generic/dso_exit.cpp, tests/meson.build
In static builds, __dso_handle should be provided by the crtbegin.o/crtend.o that is linked into the executable. This patch also fixes failing link tests when building a static gcc targeting mlibc.
=> lsb: don't provide __dso_handle for static builds

options/ansi/generic/file-io.cpp, options/ansi/generic/stdio.cpp, options/internal/generic/locale.cpp, options/internal/include/bits/nl_item.h, tests/ansi/fputs.c, tests/ansi/ftell.c, tests/meson.build
Fixes ftell behaviour after ungetc, and adds a simple test for ftell's functionality which also acts as a simple reproducible test case for the failing GMP tests documented in #1221. This test used to fail because our behaviour when checking ftell after a ungetc didn't match glibc.
Adds support for RADIXCHAR and THOUSEP in nl_langinfo, and adds some glibc aliases (not sure if they should be gated or available for all posix targets)
Fixes empty string handling in fputs and adds a simple test for fputs.
Fixes #1221.
=> various fixes for failing GMP tests

options/ansi/include/setjmp.h, options/internal/aarch64/setjmp.S, options/internal/m68k/setjmp.S, options/internal/riscv64/setjmp.S, options/internal/x86/setjmp.S, options/internal/x86_64/setjmp.S
This patch makes setjmp.h better conform to both ISO C and POSIX-2017.1 standards.
setjmp/_setjmp/longjmp/_longjmp currently act how they act in glibc systems (they both don't save the signal mask), if there is a use case for it we could also support the BSD convention (where setjmp/longjmp save the signal mask but the underscore variants don't)
=> options/ansi: provide _setjmp and _longjmp in setjmp.h

options/glibc/generic/stdio_ext.cpp, options/glibc/include/stdio_ext.h, options/glibc/include/sys/mtio.h
Needed for GNU coreutils on Linux.
=> Fixes for GNU Coreutils

abis/linux/random.h, abis/mlibc/random.h, options/linux/include/sys/random.h, sysdeps/aero/include/abi-bits/random.h, sysdeps/aero/meson.build, sysdeps/astral/include/abi-bits/random.h, sysdeps/astral/meson.build, sysdeps/keyronex/include/abi-bits/random.h, sysdeps/keyronex/meson.build, sysdeps/lemon/include/abi-bits/random.h, sysdeps/lemon/meson.build, sysdeps/linux/include/abi-bits/random.h, sysdeps/linux/meson.build, sysdeps/managarm/include/abi-bits/random.h, sysdeps/managarm/meson.build
Systemd checks the values of these, and they were wrong on the Linux ABI from the start. On the mlibc ABI they remain unchanged.
=> abis/linux: Fix wrong definition of the GRND_* constants on the Linux ABI

sysdeps/managarm/generic/file.cpp
F_DUPFD was implemented completely wrong, and systemd relied on this. This PR fixes the issues.
Blocked on managarm/managarm#848
=> sysdeps/managarm: Fix fcntl F_DUPFD and F_DUPFD_CLOEXEC

options/ansi/generic/file-io.cpp
This flag was added in C11 and POSIX.1-2024. This patch is needed for tzdata's zic timezone compiler.
=> options/ansi: add flag 'x' in modestrings

options/posix/include/ftw.h
POSIX says the inclusion of <ftw.h> may also make visible symbols from <sys/stat.h>. Out in the wild, libcap-ng seems to depend on this behaviour.
=> options/posix: include <sys/stat.h> from <ftw.h>

options/rtld/generic/linker.cpp, options/rtld/generic/linker.hpp, options/rtld/generic/main.cpp
Related to #1196, might fix the systemd issue but doesn't actually implement RPATH inheritance, simply makes RTLD search breadth-first. Will fix the `libgcc_s.so.1` issue in nixpkgs.
=> rtld: Use breadth-first search order

options/rtld/generic/linker.cpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/vinix/generic/generic.cpp
This also fixes a bug where the 'Take care of removing superfluous permissions' code wouldn't do so for the entirety of mappings made when MLIBC_MAP_DSO_SEGMENTS is set, but only for the unbacked portion
=> options/rtld: Avoid potentially mapping pages as W+X

options/glibc/generic/execinfo.cpp
This is needed for some Xorg related packages, which otherwise bail out due to the assertion here.
=> options/glibc: Stub out backtrace() function

options/posix/include/syslog.h
The `__USE_MISC` define is a GLIBC thing for BSD 4.x extensions and holds no weight in mlibc since it's already gated behind `__MLIBC_BSD_OPTION`.
=> options/posix: Remove incorect `__USE_MISC` guard

tests/ansi/sprintf.c
=> tests/ansi: add test for printf dollar argument corruption

.github/workflows/ci.yml, options/glibc/include/net/ethernet.h, options/glibc/include/sys/reg.h
The previous glob was not checking all headers. Fix this, and fix any new issues that have arisen.
=> ci: check more public headers for pedantic warnings

tests/posix/shm.c
if the system has 23123123 as a used key for a preexisting shm segment, the tests will spuriously fail. This implements a better approach.
=> tests/posix: make SHM tests more resilient to preexisting system shmids

sysdeps/menix/generic/internal.cpp
For some odd reason, this doesn't happen on x86_64, but will kill builds on aarch64, riscv64 and loongarch64...
=> sysdeps/menix: Add includes to fix builds on !x86_64

ABI_BREAKS.md, RELEASE_PROCEDURE.md
- **docs: RELEASE_PROCEDURE.md: Mention fixing of submodule commits**
- **docs: ABI_BREAKS.md: Mention versions 5 and 6 were not logged**
=> release prep

sysdeps/linux/generic/sysdeps.cpp
The syscall expects single pointers to the values, but double pointers were being passed incorrectly.
=> sysdeps/linux: Fix sys_getresuid and sys_getresgid

abis/menix/reboot.h, sysdeps/menix/include/abi-bits/reboot.h, sysdeps/menix/meson.build
This PR adds a missing abi-bit for the `menix` sysdep
=> sysdeps/menix: Fix reboot.h values

sysdeps/managarm/generic/entry.cpp, sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/managarm/include/bits/errors.hpp, sysdeps/managarm/include/mlibc/posix-pipe.hpp, sysdeps/managarm/rtld-generic/support.cpp
Since the changes are incomplete and a little unstable, marking it as draft right now.
=> Changes for managarm cancelable syscalls

options/posix/generic/posix_stdlib.cpp
mkostemp would previously pass 0 to flags and flags to suffixlen when forwarding its parameters to the mkostemps function. This commit should fix that.
=> options/posix: fix bug with mkostemp

sysdeps/managarm/generic/socket.cpp
This changes the sysdep's transmission flow to be analogous to e.g. `sockname`.
=> sysdeps/managarm: correctly handle peername errors

sysdeps/managarm/generic/file.cpp
`glib` testsuite expects this for invalid `fd` in `fsync`, and it matches spec. Return EBADF in fsync on closed fd's.
=> sysdeps/managarm: Add EBADF handling to sys_fsync

options/glibc/include/error.h
This fixes the -Wtrailing-whitespace warning when building eg: coreutils.
=> Remove trailing whitespace in error.h

sysdeps/managarm/generic/ioctl.cpp, sysdeps/managarm/generic/socket.cpp
These patches are enough to successfully run [os-test](https://sortix.org/os-test/) without crashing, at least what patching concerns the mlibc sysdep side of managarm.
=> Avoid asserting on unknown ioctls or getsockopt options
