managarm/mlibc

sysdeps/managarm/generic/file.cpp
Related to https://github.com/managarm/managarm/pull/79
=> sysdeps/managarm: add support for the DRM_IOCTL_MODE_CURSOR ioctl

options/posix/generic/unistd-stubs.cpp
=> Add getopt

sysdeps/managarm/generic/file.cpp
related pr: https://github.com/managarm/managarm/pull/118
=> sysdeps/managarm: migrate sys_msg_recv/send to fs

ci/Jenkinsfile, ci/bootstrap.yml, ci/docker/Dockerfile, ci/docker/gitconfig
adding tests would be trivial: adding another stage inside Docker that runs the tests
=> ci: add files needed to build with jenkins

internal-config.h.in, meson.build, options/rtdl/generic/linker.cpp, options/rtdl/generic/linker.hpp, options/rtdl/generic/main.cpp, options/rtdl/x86_64/entry.S, options/rtdl/x86_64/runtime.S, sysdeps/linux/generic/entry.cpp, sysdeps/linux/x86_64-crt/crt1.S
Rudimentary fixes for #29. Probably could use some style improvements...
=> Integrate ld.so into static build

options/posix/generic/sys-stat-stubs.cpp
This change is required for gzip to work.
=> options/posix: Stubbed fchmod()

options/posix/generic/dirent-stubs.cpp, sysdeps/managarm/generic/file.cpp
This is required for grep to work recursively.
Furthermore, this patch adds fcntl(F_SETFD) support to managarm's sysdeps.
=> posix: Implemented fdopendir

options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/fcntl.h, sysdeps/managarm/generic/file.cpp
=> options/posix: Implemented faccessat()

options/glibc/generic/stdio_ext-stubs.cpp
=> options/glibc: Implemented __freadahead()

abis/mlibc/in.h, options/ansi/include/limits.h, options/glibc/generic/resolv-stubs.cpp, options/glibc/include/endian.h, options/glibc/include/resolv.h, options/glibc/meson.build, options/linux/generic/netinet-in6addr.cpp, options/linux/include/linux/netlink.h, options/linux/include/linux/rtnetlink.h, options/linux/include/mntent.h, options/linux/include/poll.h, options/linux/include/sys/inotify.h, options/linux/include/sys/poll.h, options/linux/meson.build, options/posix/generic/pthread-stubs.cpp, options/posix/generic/pwd-stubs.cpp, options/posix/generic/spawn-stubs.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/netinet/in.h, options/posix/include/pthread.h, options/posix/include/pwd.h, options/posix/include/spawn.h, options/posix/include/sys/param.h, options/posix/include/unistd.h
This is a work in progress PR with all the changes needed for glib to compile, I'll update this later when more work is done
=> Various fixes and new functions for glib to work

options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/unistd-stubs.cpp, sysdeps/managarm/generic/file.cpp
sysdeps/managarm: Implemented link and linkat
=> options/posix: Implemented link and linkat

options/ansi/generic/stdlib-stubs.cpp, options/posix/include/netdb.h, options/posix/include/sys/types.h
rand_r is implemented like musl
=> Various fixes for libressl and shared-mime-info

options/ansi/generic/string-stubs.cpp, options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/unistd-stubs.cpp, sysdeps/managarm/generic/fork-exec.cpp
This PR aims to implement get/set(e)uid and friends for managarm.
It also holds a small bugfix in `strerror` where EPERM was listed as EFAULT
=> managarm: Implement various uid/gid functions

options/internal/include/mlibc/sysdeps.hpp, options/posix/generic/grp-stubs.cpp, options/posix/generic/pwd-stubs.cpp, options/posix/generic/sys-stat-stubs.cpp, sysdeps/managarm/generic/file.cpp
This PR aims to implement the following functions related to file permissions
- `chmod()`
- `fchmod()`
- `fchmodat()`
Note the use of `AT_EMPTY_PATH` in `sys_fchmod()`, this is not specified by posix and a managarm extension.
=> managarm: Implement various file permission functions

abis/linux/x86_64/termios.h, abis/mlibc/in.h, abis/mlibc/termios.h, options/ansi/include/limits.h, options/glibc/generic/resolv-stubs.cpp, options/glibc/include/resolv.h, options/linux/include/sys/poll.h, options/posix/generic/grp-stubs.cpp, options/posix/generic/netdb-stubs.cpp, options/posix/generic/syslog-stubs.cpp, options/posix/include/grp.h, options/posix/include/netdb.h, options/posix/include/sys/param.h, options/posix/include/sys/time.h, options/posix/include/termios.h, sysdeps/lemon/include/abi-bits/termios.h, sysdeps/lemon/meson.build, sysdeps/linux/include/abi-bits/termios.h, sysdeps/linux/meson.build, sysdeps/managarm/include/abi-bits/termios.h, sysdeps/managarm/meson.build, sysdeps/qword/include/abi-bits/termios.h, sysdeps/qword/meson.build, sysdeps/sigma/include/abi-bits/termios.h, sysdeps/sigma/meson.build
This PR aims to implement the required functionality for `socat` to compile.
So far, only the build time errors have bee resolved, the link time errors are still there.
=> Various fixes for socat

options/ansi/generic/file-io.cpp, options/ansi/generic/stdio-stubs.cpp, options/ansi/generic/time-stubs.cpp, options/ansi/include/mlibc/file-io.hpp, options/internal/include/mlibc/allocator.hpp, options/internal/include/mlibc/lock.hpp, options/posix/generic/dirent-stubs.cpp
=> scandir(), ansi/time-stubs.cpp fixes and file locking

sysdeps/managarm/generic/socket.cpp
This PR allows `udevd` to function again
Blocked on the corresponding managarm PR (managarm/managarm#187)
=> Implement sys_listen

options/ansi/generic/file-io.cpp, options/posix/generic/sys-select-stubs.cpp
Fixes #111 and a ``select()`` regression
=> Fix regressions in select() and fflush()

options/posix/generic/lookup.cpp, options/posix/generic/netdb-stubs.cpp, options/posix/include/mlibc/lookup.hpp
Fixes #90 . Imo the code is a bit ugly but I didn't see a way to make it substantially prettier. Let me know if I missed something. ``gethostbyname()`` was tested with sysklogd on managarm and seems to work, along with my own testing of the function.
=> implement gethostbyname() and a getaddrinfo() fix

sysdeps/dripos/generic/generic.cpp, sysdeps/dripos/generic/thread.cpp, sysdeps/dripos/generic/thread_entry.S, sysdeps/dripos/include/mlibc/thread-entry.hpp, sysdeps/dripos/meson.build
=> add threading support to dripos sysdeps

options/ansi/generic/signal-stubs.cpp, options/posix/generic/sys-uio.cpp, sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/fork-exec.cpp
As discussed in the Discord, this PR holds all the changes required in mlibc
Blocked on managarm/managarm#201
=> Various fixes required for Xwayland support in managarm

options/posix/generic/lookup.cpp, options/posix/generic/netdb-stubs.cpp, options/posix/generic/resolv_conf.cpp, options/posix/generic/services.cpp, options/posix/include/mlibc/lookup.hpp, options/posix/include/mlibc/resolv_conf.hpp, options/posix/include/mlibc/services.hpp, options/posix/include/netdb.h, options/posix/meson.build
Crosses off 4/5 points currently listed on issue #99, mainly:
- add ``/etc/services`` parsing
- add ``/etc/resolv.conf`` parsing
- add ``/etc/hosts`` parsing
- deal with CNAME dns cleaning up the alias related code
=> various name resolving related improvements

options/posix/generic/sys-shm.cpp
This change is needed to run `glxgears` in Managarm.
=> options/posix: Stubbed shmget()

options/posix/generic/arpa-inet-stubs.cpp, sysdeps/linux/meson.build, sysdeps/linux/mlibc-gcc, sysdeps/linux/mlibc-gcc.in, sysdeps/linux/mlibc-gcc.specs.in
Fixes #112 and makes ``mlibc-gcc`` more portable across distro's
=> mlibc-gcc fixed and inet_pton implementation

.github/workflows/ci.yml, ci/bootstrap.yml, meson.build, meson_options.txt, sysdeps/dripos/meson.build, sysdeps/lemon/meson.build, sysdeps/linux/meson.build, sysdeps/managarm/meson.build, sysdeps/qword/meson.build, sysdeps/sigma/meson.build, tests/ansi/sprintf.c, tests/ansi/sscanf.c, tests/meson.build, tests/posix/inet_ntop.c, tests/posix/inet_pton.c
Also includes the ``--with-specs`` configure flag for gcc
=> Add basic test infrastructure

options/glibc/include/getopt.h
=> options/glibc: add opt* declarations to getopt.h

options/ansi/generic/stdio-stubs.cpp, tests/ansi/snprintf.c, tests/ansi/sprintf.c, tests/meson.build
Fixes #118 and adds tests for #58.
=> vsnprintf fixes and printf testing

abis/linux/x86_64/socket.h, abis/mlibc/in.h, abis/mlibc/socket.h, options/glibc/include/sys/ioctl.h, options/posix/include/sys/socket.h
This PR adds 4 network related constants, 2 ioctl constants and 2 structs, all shamelessly borrowed from my host.
=> Add some defines and structs required by cmake

abis/dripos/auxv.h, abis/lemon/auxv.h, abis/linux/x86_64/auxv.h, abis/managarm/auxv.h, abis/qword/auxv.h, abis/sigma/auxv.h, ci/bootstrap.yml, meson.build, options/internal/gcc/stack_protector.cpp, options/internal/include/mlibc/stack_protector.hpp, options/internal/include/mlibc/tcb.hpp, options/rtdl/generic/linker.cpp, options/rtdl/generic/main.cpp
=> Add stack protector support

options/ansi/generic/stdio-stubs.cpp, tests/ansi/locale.c
this PR won't build it's waiting on [frigg/#5](https://github.com/managarm/frigg/pull/5). Also the test for ``%lc`` is disabled because it currently crashes due to a missing locale implementation, but leaving it there for future use.
=> Formatting

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/socket.cpp
This PR changes some hard failures that are just assertions about not implemented features into soft failures, thus allowing `curl` to proceed further in Managarm.
=> Improve error handling for curl

abis/linux/x86_64/signal.h, abis/mlibc/resource.h, abis/mlibc/signal.h, options/ansi/generic/signal-stubs.cpp, options/ansi/generic/stdlib-stubs.cpp, options/ansi/include/setjmp.h, options/internal/include/bits/machine.h, options/internal/x86/setjmp.S, options/internal/x86_64/setjmp.S, options/posix/generic/grp-stubs.cpp, options/posix/generic/posix_signal.cpp, options/posix/include/grp.h, options/posix/include/pwd.h, options/posix/include/sys/socket.h
In preparation for release 2.0
=> Merge abi-break branch

options/posix/generic/posix_stdio.cpp, sysdeps/linux/generic/sysdeps.cpp, tests/meson.build, tests/posix/dprintf.c
=> Don't close fd in dprintf

options/elf/include/elf.h
This PR fixes mesa on Managarm.
=> options/elf: Add Elf32_Nhdr and Elf64_Nhdr

sysdeps/managarm/generic/socket.cpp
We also handle ENOENT correctly now in `sys_connect()`, the managarm side is yet to be changed (soon), but this pr is not blocked on that change.
=> sysdeps/managarm: Fix bug in sys_connect and convert to helix_ng

sysdeps/managarm/generic/entry.cpp
This PR makes managarm use the generic entry code instead of some custom thing. This fixes #41
=> sysdeps/managarm: Change the startup code to use the generic version

sysdeps/managarm/generic/signals.cpp
This is the mlibc counterpart of the signal changes in managarm/managarm#246
=> sysdeps/managarm: Handle EINVAL in sigaction

options/posix/generic/posix_signal.cpp, options/posix/include/bits/posix/posix_signal.h
I added a stub, as sigaction is not yet implemented.
=> Added stub for siginterrupt

sysdeps/managarm/generic/file.cpp
This logic has been moved into the posix subsystem. It is required to allow Rust programs to start, as they use `poll` to check for the existence of fds 0-2.
Note: this code was writen by avdgrinten ;)
=> sysdeps/managarm: Remove poll/epoll flag handling

tests/ansi/sprintf.c
Adds tests for the additions in managarm/frigg#6.
The CI will fail until that PR has been merged.
=> tests/sprintf: add tests for # and +

options/ansi/generic/stdio-stubs.cpp, tests/meson.build, tests/posix/getdelim.c
=> posix: Implement getline and getdelim

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/managarm/generic/signals.cpp, sysdeps/managarm/generic/socket.cpp, sysdeps/managarm/rtdl-generic/support.cpp
Depends on https://github.com/managarm/managarm/pull/271/
=> sysdeps/managarm: replace parseSimple with parseHandle for offer

tests/ansi/sprintf.c
To complement managarm/frigg#7.
=> tests/sprintf: add tests for managarm/frigg#7

sysdeps/managarm/generic/file.cpp
Complements managarm/managarm#274. CI will fail until the necessary changes to `bragi` have been merged.
=> sysdeps/managarm: Support ioctl(FIOCLEX)

options/posix/generic/pwd-stubs.cpp, options/posix/generic/unistd-stubs.cpp, tests/meson.build, tests/posix/pwd.c
Fixes managarm/mlibc#185 and managarm/mlibc#191.
=> options/posix: implement getpw{nam,uid}_r

options/ansi/generic/file-io.cpp, options/posix/generic/posix-file-io.cpp, options/posix/generic/posix_stdio.cpp, options/posix/include/mlibc/posix-file-io.hpp, options/posix/meson.build, tests/meson.build, tests/posix/open_memstream.c
=> Open memstream implementation and global_file_list fix

sysdeps/managarm/generic/entry.cpp, sysdeps/managarm/meson.build, sysdeps/managarm/rtdl-generic/support.cpp
This depends on managarm/managarm#366
=> sysdeps/managarm: use ManagarmProcessData defined in protocols/posix

.github/workflows/ci.yml, options/posix/generic/grp-stubs.cpp, options/posix/generic/unistd-stubs.cpp, tests/meson.build, tests/posix/grp.c, tests/posix/pwd.c
Implement `getgr{nam,gid}_r` (fixing the existing group parsing code) and also fixing the `pwd` tests.
Fixes #181.
=> options/posix: Implement `getgr{nam,gid}_r`

tests/ansi/sprintf.c
Requires https://github.com/managarm/frigg/pull/12.
=> tests/sprintf: add tests for float zero padding

meson.build
=> build: Fix missing header install

options/posix/generic/unistd-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp
https://www.youtube.com/watch?v=wL3X0hfDXvM
=> unistd: implement getgroups()

options/posix/include/net/if.h
@Geertiebear this one is for you. This PR allows `cups` to compile on Managarm (a corresponding PR in bootstrap will follow shortly).
=> options/posix: Add two defines related to network interfaces

options/posix/include/sys/resource.h
Does exactly that. Feel a bit silly doing a PR for just this but I don't need to change anything else and you'll need to have it at some point.
=> posix: add mising define RLIM_NLIMITS

options/ansi/generic/time-stubs.cpp, tests/ansi/time.c, tests/meson.build
This PR partially implements strptime() and adds tests for the parts which are implemented. Most of the unimplemented parts depend on locale functionality. Issue #276 is related to this.
=> Implement strptime().

RELEASE_PROCEDURE.md
Open to suggestions and comments here for sure.
=> meta: add a release procedure

options/posix/generic/netdb-stubs.cpp, options/posix/generic/services.cpp, options/posix/include/mlibc/services.hpp, tests/meson.build, tests/posix/getservbyport.c
=> options/posix: implement getservbyport()

options/elf/generic/phdr.cpp, options/elf/include/link.h, options/rtdl/generic/linker.cpp, options/rtdl/generic/linker.hpp, options/rtdl/generic/main.cpp, tests/meson.build, tests/rtdl/dl_iterate_phdr.c
=> Implement dl_iterate_phdr

options/posix/generic/netdb-stubs.cpp, tests/meson.build, tests/posix/getservbyname.c
=> options/posix: implement getservbyname

sysdeps/managarm/generic/file.cpp
Implement the `FIONREAD` ioctl. This depends on the other half of the PR in managarm, managarm/managarm#410.
This obsoletes #241.
=> Implement FIONREAD ioctl

options/posix/generic/resolv_conf.cpp, options/rtdl/generic/linker.cpp
=> options/posix: fix frigg error

abis/mlibc/fcntl.h, options/linux-headers/include/linux/memfd.h, options/linux-headers/meson.build, options/posix/generic/sys-mman-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, options/posix/include/sys/mman.h, sysdeps/managarm/generic/file.cpp
This is the mlibc counterpart to managarm/managarm#418.
=> Implement memfd and file sealing

tests/ansi/sprintf.c
Adds tests for https://github.com/managarm/frigg/pull/22.
=> tests/ansi: check %h and %hh printf length modifiers

ci/bootstrap.yml, options/ansi/generic/file-io.cpp, options/ansi/musl-generic-math/libm.h, options/glibc/meson.build
This should fix the ansi only build on the ci.
=> ci: Several glibc related fixes

abis/linux/x86_64/vm-flags.h, abis/mlibc/abi.h, abis/mlibc/socket.h, abis/mlibc/vm-flags.h, options/ansi/generic/errno-stubs.cpp, options/ansi/include/errno.h, options/linux/generic/pty-stubs.cpp, options/posix/include/fcntl.h, options/posix/include/netinet/tcp.h, options/posix/include/sys/mman.h, options/posix/include/termios.h
Also moves some defines from mman.h into abi bits.
=> abis,options: add missing defines for alacritty

abis/mlibc/errno.h, options/ansi/include/inttypes.h, options/posix/generic/posix_stdlib.cpp, options/posix/generic/sys-resource-stubs.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/bits/posix/posix_stdlib.h, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/managarm/generic/file.cpp, tests/bsd/reallocarray.c, tests/meson.build, tests/posix/alarm.c, tests/posix/setpriority.c
This PR adds mlibc work that eventually should allow X.org to run in pure X mode on Managarm. As we're kinda stuck at the moment, this should be merged now, and any additional work can go into it's own PR. Notably lacking is a regex suite, we should settle on one to copy or implement our own.
=> Various additions to make pure X work on Managarm

ci/bootstrap.yml, meson.build, options/ansi/generic/stdlib-stubs.cpp, options/ansi/generic/time-stubs.cpp, options/glibc/generic/shadow-stubs.cpp, options/iconv/generic/iconv-stubs.cpp, options/internal/include/mlibc/file-window.hpp, options/intl/generic/libintl-stubs.cpp, options/posix/generic/posix_stdio.cpp, options/posix/generic/sys-mman-stubs.cpp, options/posix/generic/sys-time-stubs.cpp, options/posix/generic/unistd-stubs.cpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/managarm/generic/file.cpp, tests/ansi/strchr.c, tests/ansi/strrchr.c, tests/ansi/strverscmp.c, tests/bsd/ns_get_put.c, tests/posix/abort.c, tests/posix/ffs.c, tests/posix/getdelim.c, tests/posix/index.c, tests/posix/open_memstream.c, tests/posix/popen.c, tests/posix/posix_spawn.c, tests/posix/pwd.c, tests/posix/realpath.c, tests/posix/rindex.c
Supercedes https://github.com/managarm/mlibc/pull/436.
=> meta: fix all warnings and enable -Werror on CI

abis/aero/auxv.h, abis/dripos/auxv.h, abis/lemon/auxv.h, abis/linux/x86_64/auxv.h, abis/qword/auxv.h, abis/sigma/auxv.h, options/posix/generic/posix_stdlib.cpp, options/rtdl/generic/main.cpp
Not quite sure how to test this one.
=> options/posix: implement secure_getenv

options/posix/generic/pthread-stubs.cpp
Fixes https://github.com/managarm/mlibc/issues/469.
=> options/posix: loop if sys_futex_wait returns EAGAIN

abis/mlibc/in.h, options/glibc/include/sys/procfs.h, options/glibc/include/sys/reg.h, options/glibc/meson.build, options/internal/include/mlibc/file-window.hpp, options/linux/generic/netinet-in6addr.cpp, options/linux/meson.build, options/posix/generic/arpa-inet-stubs.cpp, options/posix/generic/sys-stat-stubs.cpp, options/posix/include/netinet/in.h
This PR is part of the mlibc on Linux project.
=> Various additions for mlibc on Linux project

options/elf/include/elf.h, options/posix/generic/dlfcn-stubs.cpp, options/posix/include/dlfcn.h, options/posix/include/glob.h, options/rtdl/generic/linker.cpp, options/rtdl/generic/main.cpp
Fixes some minor issues and suppresses some logging spam.
Split from #448. Fixes #450.
=> rtdl: minor additions and bug fixes

options/internal/include/mlibc/strtol.hpp
This should make UBSan happy. Blocked on https://github.com/managarm/cxxshim/pull/12.
=> options/posix: fix strtol behaviour on LONG_MIN

.github/workflows/ci.yml, ci/bootstrap.yml
=> ci: build headers-only and only build gcc once

options/ansi/generic/locale-stubs.cpp
This should reduce some log spam.
=> options/ansi: handle LC_MESSAGES in setlocale

options/glibc/include/sys/ioctl.h
=> options/glibc: Define some additional ioctl's

abis/linux/fcntl.h
=> abis/linux: Define the F_SEAL_ family

options/posix/include/sys/ttydefaults.h
=> options/posix: Define CREPRINT and CDISCARD

options/elf/include/elf.h
=> options/elf: Define various missing structs

abis/linux/epoll.h, abis/mlibc/epoll.h, options/linux/include/sys/epoll.h, sysdeps/aero/include/abi-bits/epoll.h, sysdeps/aero/meson.build, sysdeps/dripos/include/abi-bits/epoll.h, sysdeps/dripos/meson.build, sysdeps/ironclad/include/abi-bits/epoll.h, sysdeps/ironclad/meson.build, sysdeps/lemon/include/abi-bits/epoll.h, sysdeps/lemon/meson.build, sysdeps/linux/include/abi-bits/epoll.h, sysdeps/linux/meson.build, sysdeps/managarm/include/abi-bits/epoll.h, sysdeps/managarm/meson.build, sysdeps/qword/include/abi-bits/epoll.h, sysdeps/qword/meson.build
=> abis: Split off EPOLL_CLOEXEC into it's own abi header

tests/ansi/alloc.c, tests/ansi/wcsdup.c, tests/ansi/wmemcmp.c, tests/bsd/ns_get_put.c, tests/bsd/reallocarray.c, tests/meson.build, tests/posix/getcwd.c, tests/posix/grp.c, tests/posix/open_memstream.c, tests/posix/posix_memalign.c, tests/posix/pwd.c, tests/posix/search.c, tests/posix/sigaltstack.c, tests/posix/wordexp.c
=> tests: run host tests with sanitizers

sysdeps/linux/generic/sysdeps.cpp, sysdeps/linux/x86_64/abi-bits/arch-syscall.h
=> sysdeps/linux: Implement sys_clock_getres

options/posix/generic/unistd-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, options/posix/include/unistd.h
=> options/posix: Implement setresuid and setresgid

options/ansi/generic/wchar-stubs.cpp, options/posix/generic/langinfo-stubs.cpp, tests/meson.build, tests/posix/wcwidth.c
=> Implement wc(s)width and ABMON_1..12 in nl_langinfo

options/posix/generic/pthread-stubs.cpp, options/posix/include/pthread.h, tests/posix/pthread_rwlock.c
Progress on #530. Continued from #605.
=> options/posix: implement pthread_rwlockattr

options/ansi/include/limits.h, options/posix/generic/unistd-stubs.cpp, options/posix/include/unistd.h
Commit taken from the Vinix patches.
=> ansi: add RE_DUP_MAX and CHARCLASS_NAME_MAX

options/posix/generic/dlfcn-stubs.cpp, options/rtdl/generic/linker.cpp, options/rtdl/generic/linker.hpp, options/rtdl/generic/main.cpp, tests/rtdl/meson.build, tests/rtdl/rtld_next/libbar.c, tests/rtdl/rtld_next/libfoo.c, tests/rtdl/rtld_next/meson.build, tests/rtdl/rtld_next/test.c
Fixes #577. Split off from #448. Blocked on the new RTDL testing framework in #586 so I can add a meaningful test for this.
=> rtdl: implement RTLD_NEXT

options/ansi/generic/stdlib-stubs.cpp, tests/ansi/utf8.c, tests/meson.build
=> options/ansi: implement mbtowc

options/linux/include/net/if_arp.h
=> options/linux: Add struct arpreq

ABI_BREAKS.md, abis/mlibc/utsname.h
As per the discussion in #504.
=> abi-bits: add domainname to utsname in mlibc abi

options/ansi/generic/file-io.cpp, options/ansi/generic/stdio-stubs.cpp, options/ansi/include/mlibc/file-io.hpp, options/internal/include/mlibc/lock.hpp, options/internal/include/mlibc/tid.hpp, options/posix/generic/pthread-stubs.cpp, tests/meson.build, tests/posix/flockfile.c
Fixes #408. We also implement `ftrylockfile`.
=> options: allow recursive file locking

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/socket.cpp, sysdeps/managarm/rtdl-generic/support.cpp
Implements the ioctls for DRM PRIME, which depend on bragi additions in managarm.
=> sysdeps/managarm: Implement DRM PRIME ioctls

options/posix/generic/posix-file-io.cpp
=> options/posix: initialize mem_file::_pos to zero

sysdeps/linux/generic/sysdeps.cpp, sysdeps/linux/x86_64/abi-bits/arch-syscall.h
=> sysdeps/linux: Add sys_yield

sysdeps/managarm/generic/fork-exec.cpp
=> sysdeps/managarm: hack sys_gettid

.github/workflows/abidiff.yml
=> gha: rename abidiff workflow to be more clear

ci/bootstrap.yml, options/posix/include/sys/mman.h
Now that we have `sys/syscall.h`, this should work.
=> ci: build libgcc

options/internal/include/mlibc/lock.hpp, options/posix/generic/pthread-stubs.cpp
See discussion in https://github.com/managarm/mlibc/pull/600#issuecomment-1173013036.
=> options/posix: fix potential use-after-free in pthread_mutex_unlock

options/bsd/include/fstab.h, options/bsd/meson.build
=> options/bsd: Add fstab.h header

options/posix/generic/sys-mman-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/linux/x86_64/abi-bits/arch-syscall.h
=> options/posix: Implement msync

options/posix/generic/posix_stdio.cpp, options/posix/include/bits/posix/posix_stdio.h
=> options/posix: Stub fgetln

options/posix/generic/pthread-stubs.cpp, options/posix/include/pthread.h, tests/meson.build, tests/posix/pthread_mutex.c
=> options/posix: implement pthread_mutexattr

options/posix/generic/unistd-stubs.cpp, options/posix/include/unistd.h
=> options/posix: Stub get and setdomainname

abis/linux/shm.h, options/posix/include/sys/shm.h, sysdeps/aero/include/abi-bits/shm.h, sysdeps/aero/meson.build, sysdeps/dripos/include/abi-bits/shm.h, sysdeps/dripos/meson.build, sysdeps/ironclad/include/abi-bits/shm.h, sysdeps/ironclad/meson.build, sysdeps/lemon/include/abi-bits/shm.h, sysdeps/lemon/meson.build, sysdeps/linux/include/abi-bits/shm.h, sysdeps/linux/meson.build, sysdeps/managarm/include/abi-bits/shm.h, sysdeps/managarm/meson.build, sysdeps/vinix/include/abi-bits/shm.h, sysdeps/vinix/meson.build
=> abis: Add struct shm_info

options/posix/generic/pthread-stubs.cpp, options/posix/include/pthread.h, tests/posix/pthread_cond.c
=> options/posix: implement pthread_condattr

options/posix/generic/netdb-stubs.cpp, options/posix/generic/posix_signal.cpp, options/posix/generic/unistd-stubs.cpp, options/posix/include/bits/posix/posix_signal.h, options/posix/include/netdb.h, options/posix/include/unistd.h
=> options/posix: Stub several functions

options/posix/generic/pthread-stubs.cpp, options/posix/include/pthread.h, tests/meson.build, tests/posix/pthread_barrier.c
=> options/posix: implement pthread_barrier

options/posix/generic/pthread-stubs.cpp
It's possible that tgkill fails in pthread_cancel because the cancelee
has in the quit in the time between setting the cancellation trigger
bit, and sending SIGCANCEL.
Fixes #613
=> options/posix: fix race with cancelee in pthread_cancel

abis/linux/mqueue.h, options/posix/include/mqueue.h, options/posix/meson.build, sysdeps/aero/include/abi-bits/mqueue.h, sysdeps/aero/meson.build, sysdeps/dripos/include/abi-bits/mqueue.h, sysdeps/dripos/meson.build, sysdeps/ironclad/include/abi-bits/mqueue.h, sysdeps/ironclad/meson.build, sysdeps/lemon/include/abi-bits/mqueue.h, sysdeps/lemon/meson.build, sysdeps/linux/include/abi-bits/mqueue.h, sysdeps/linux/meson.build, sysdeps/managarm/include/abi-bits/mqueue.h, sysdeps/managarm/meson.build, sysdeps/vinix/include/abi-bits/mqueue.h, sysdeps/vinix/meson.build
=> options/posix: Add mqueue header

sysdeps/managarm/generic/entry.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/managarm/generic/memory.cpp, sysdeps/managarm/generic/signals.cpp, sysdeps/managarm/rtdl-generic/support.cpp
Depends on managarm/managarm#470
=> managarm: fix sys_futex_tid by turning it into a supercall

options/linux/generic/sched.cpp, options/linux/include/bits/linux/linux_sched.h, options/linux/include/mlibc/linux-sysdeps.hpp, options/linux/meson.build, options/posix/generic/netdb-stubs.cpp, options/posix/generic/sched-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, options/posix/include/netdb.h, options/posix/include/sched.h, sysdeps/linux/generic/sysdeps.cpp
=> Linux sysdep additions and stubbing from LFS

sysdeps/managarm/generic/file.cpp
Depends on managarm/managarm#480.
=> sysdeps/managarm: convert file.cpp to helix_ng

sysdeps/managarm/generic/file.cpp
It turns out that we were telling Managarm that we were going to send a bragi head and tail, while only sending a head. We were also missing the buffer with stuff to write. Whoops, this PR fixes that.
=> sysdeps/managarm: Fix sys_pwrite

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/socket.cpp
This PR addresses some missing error handling and stubs a setsockopt call that curl makes. Together with managarm/managarm#482 this fixes curl.
=> Some small fixes for curl

options/posix/include/sys/mman.h
Found while compiling systemd.
=> options/posix: Add missing mlibc-config.h include

options/bsd/include/arpa/nameser.h, options/posix/include/netinet/in.h, sysdeps/managarm/generic/socket.cpp
This PR includes three small fixes needed to make `OpenSSH` compile and run somewhat. Debugging isn't finished yet and as of writing it doesn't fully work, but small PRs should get merged quicker, I hope.
=> Some OpenSSH fixes

meson.build, options/ansi/generic/fenv-stubs.cpp, options/ansi/include/bits/ansi/fenv.h, options/ansi/include/fenv.h, options/internal/aarch64/fenv.S, options/internal/riscv64/fenv.S, options/internal/x86_64/fenv.S, tests/ansi/fenv.c, tests/meson.build
Chromium made extensive use of some of these functions, so I decided to implement them like musl does. Fixes some ensures in Chromium.
=> options/ansi: Implement several of the fenv family functions

options/ansi/meson.build
Likely fixes some build errors we found.
=> options/ansi: Add missing install line

sysdeps/managarm/generic/socket.cpp
Adds some missing error handling.
=> sysdeps/managarm: Add additional error handling to sys_bind

abis/mlibc/poll.h, options/posix/generic/sys-mman-stubs.cpp
Needed to update the rust crate `nix` to a newer version.
=> Some minor rust fixes

sysdeps/aero/generic/filesystem.cpp
The `sys_pselect` sysdep is implemented via epoll(7).
Signed-off-by: Andy-Python-Programmer <andypythonappdeveloper@gmail.com>
=> sysdeps::aero: implement `sys_pselect`

abis/mlibc/in.h, options/posix/generic/arpa-inet-stubs.cpp, options/posix/generic/posix_stdlib.cpp, options/posix/include/sys/param.h, tests/posix/inet_ntop.c
Part of the mlibc LFS Project:tm:
=> LFS: minor fixes 2

sysdeps/managarm/generic/file.cpp
Counterpart of managarm/mlibc#523
=> sysdeps/managarm: Rewrite two sysdeps to the new bragi message

options/posix/generic/pthread-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/managarm/generic/fork-exec.cpp, tests/linux/pthread_setname_np.c, tests/meson.build
Blocked on managarm/managarm#522
=> Implement `pthread_[sg]etname_np`

abis/mlibc/errno.h, abis/mlibc/in.h, abis/mlibc/socket.h, options/bsd/generic/ether.cpp, options/bsd/include/netinet/ether.h, options/glibc/generic/gshadow.cpp, options/glibc/include/gshadow.h, options/glibc/include/net/ethernet.h, options/glibc/meson.build, options/linux/generic/sys-quota.cpp, options/linux/include/sys/quota.h, options/linux/meson.build, options/posix/generic/arpa-inet-stubs.cpp, options/posix/generic/sched-stubs.cpp, options/posix/include/arpa/inet.h, options/posix/include/netinet/ip.h, options/posix/include/netinet/ip6.h, options/posix/include/netinet/udp.h, options/posix/include/sched.h
Mostly defines, a few new headers and 9 function stubs. Part 5 of the systemd master PR.
=> More More stubs and header additions from #768 for systemd

abis/mlibc/seek-whence.h, options/ansi/include/math.h, options/glibc/generic/sys-timex.cpp, options/glibc/include/sys/timex.h, options/glibc/meson.build, options/posix/generic/fcntl-stubs.cpp, options/posix/generic/poll.cpp, options/posix/generic/posix_signal.cpp, options/posix/generic/posix_stdlib.cpp, options/posix/generic/pthread-stubs.cpp, options/posix/generic/sys-resource-stubs.cpp, options/posix/include/bits/posix/posix_signal.h, options/posix/include/bits/posix/posix_stdlib.h, options/posix/include/dirent.h, options/posix/include/fcntl.h, options/posix/include/pthread.h, options/posix/include/sys/poll.h, options/posix/include/sys/resource.h
A few defines, 2 structs, 1 implemented function and 6 function stubs. Part 7 of the systemd master PR.
=> More stubs and header additions from #768 for systemd

abis/mlibc/errno.h, abis/mlibc/in.h, abis/mlibc/socket.h, options/linux/generic/capabilities.cpp, options/linux/meson.build, options/posix/include/bits/posix/posix_stdio.h, options/posix/include/ftw.h, options/posix/include/netinet/tcp.h, options/posix/include/netinet/udp.h
HARD BLOCKED ON #766, #773, #776, #823, #824, #825, #826 (all have been merged!)
~~This PR is my internal staging area for systemd. I will cherry-pick commits into smaller chunks, that are actually reviewable, as this is of course not doable.~~
This was the systemd master staging PR, which has been split out in the PRs linked above. I found it fitting to finish with it. This PR adds some defines, adds one struct, and stubs 2 functions that don't need to be exported in a header.
=> Various header additions for systemd

options/glibc/generic/malloc.cpp, options/glibc/include/bits/glibc/glibc_malloc.h, options/glibc/meson.build, options/linux/generic/malloc.cpp, options/linux/include/malloc.h, tests/linux/malloc-usable-size.c, tests/meson.build
Hard-depends on managarm/frigg#59. CI will also fail until that is merged.
=> implement `malloc_usable_size`

options/ansi/generic/threads.cpp, options/ansi/include/threads.h
=> options/ansi: Stub missing C11 threads functions

sysdeps/keyronex/generic/entry.cpp, sysdeps/keyronex/generic/generic.cpp, sysdeps/keyronex/generic/linux.cpp, sysdeps/keyronex/generic/signal.cpp, sysdeps/keyronex/generic/socket.cpp, sysdeps/keyronex/generic/thread.cpp, sysdeps/keyronex/include/keyronex/syscall.h, sysdeps/keyronex/meson.build
This adds socket, epoll, and other new sysdeps to the Keyronex port, and makes signals work.
=> sysdeps/keyronex: Merge latest improvements to these.

options/ansi/generic/stdlib-stubs.cpp
This tries to handle some errors from decode_wtranscode() in mbtowc.
=> stdlib-stubs: basic error handling in mbtowc

meson.build, scripts/hdoc.toml.in
Counterpart to managarm/bootstrap-managarm#255.
=> Add hdoc support

options/glibc/generic/sys-io.cpp, options/glibc/include/mlibc/glibc-sysdeps.hpp, options/glibc/include/sys/io.h, options/glibc/meson.build, sysdeps/linux/generic/sysdeps.cpp
=> options/glibc: Add iopl, ioperm and the port i/o functions

abis/linux/msg.h, options/posix/include/sys/msg.h, sysdeps/aero/include/abi-bits/msg.h, sysdeps/aero/meson.build, sysdeps/dripos/include/abi-bits/msg.h, sysdeps/dripos/meson.build, sysdeps/ironclad/include/abi-bits/msg.h, sysdeps/ironclad/meson.build, sysdeps/keyronex/include/abi-bits/msg.h, sysdeps/lemon/include/abi-bits/msg.h, sysdeps/lemon/meson.build, sysdeps/linux/include/abi-bits/msg.h, sysdeps/linux/meson.build, sysdeps/lyre/include/abi-bits/msg.h, sysdeps/lyre/meson.build, sysdeps/managarm/include/abi-bits/msg.h, sysdeps/managarm/meson.build
=> abis: Define struct msqid_ds

options/elf/include/elf.h
=> options/elf: Match ELF64_ST_* to their ELF32_ST_* counterparts

sysdeps/managarm/generic/file.cpp
=> sysdeps/managarm: Do a slightly better job at stubbing F_GETLK

options/elf/include/elf.h, options/glibc/include/endian.h
=> Some Linux kernel build fixes

sysdeps/managarm/generic/file.cpp
mlibc counterpart to managarm/managarm#566.
=> sysdeps/managarm: Handle O_APPEND

abis/linux/gid_t.h, abis/linux/uid_t.h
=> abis/linux: Fix the signage of uid_t and gid_t

options/linux/generic/sched.cpp, options/linux/include/mlibc/linux-sysdeps.hpp, options/posix/generic/pthread-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/managarm/generic/sched.cpp, sysdeps/managarm/meson.build
Depends on [managarm#574](https://github.com/managarm/managarm/pull/574).
=> pthread, sysdeps/managarm: add set/get affinity calls

options/linux/generic/sched.cpp, sysdeps/managarm/generic/sched.cpp
Depends on https://github.com/managarm/managarm/pull/581
=> sysdeps/managarm: Implement sys_getcpu

options/ansi/generic/assert-stubs.cpp, options/ansi/include/assert.h, options/glibc/generic/glibc-assert.cpp, options/glibc/include/bits/glibc/glibc_assert.h
=> Mark assert as noreturn

options/elf/include/elf.h
=> options/elf: add some missing EM_* options

options/ansi/generic/time-stubs.cpp, options/posix/generic/posix_stdlib.cpp, options/posix/include/bits/posix/posix_stdlib.h
It's a hack, but it works good enough for discord in webkitgtk.
=> options/ansi: Implement clock_nanosleep naively

options/bsd/generic/arpa-nameser-stubs.cpp, options/bsd/include/arpa/nameser.h, options/posix/generic/netdb-stubs.cpp, options/posix/include/netdb.h
This PR adds a few new structs and stubs 4 new functions to allow `keyutils` to compile.
=> Additions for keyutils

options/internal/include/mlibc/strtofp.hpp, tests/ansi/strtof.c, tests/meson.build
Support INF/INFINITY/nan/NAN, hex floats and exponents.
=> options/internal: Improve float parsing

options/posix/generic/sys-wait-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/linux/generic/sysdeps.cpp, sysdeps/managarm/generic/fork-exec.cpp, tests/meson.build, tests/posix/waitid.c
Blocked on managarm/managarm#623.
=> options/posix: Implement waitid

abis/linux/statx.h, options/linux/generic/sys-statx.cpp, options/linux/include/bits/linux/linux_stat.h, options/linux/include/mlibc/linux-sysdeps.hpp, options/linux/meson.build, options/posix/include/sys/stat.h, sysdeps/aero/include/abi-bits/statx.h, sysdeps/aero/meson.build, sysdeps/dripos/include/abi-bits/statx.h, sysdeps/dripos/meson.build, sysdeps/ironclad/include/abi-bits/statx.h, sysdeps/ironclad/meson.build, sysdeps/keyronex/include/abi-bits/statx.h, sysdeps/keyronex/meson.build, sysdeps/lemon/include/abi-bits/statx.h, sysdeps/lemon/meson.build, sysdeps/linux/generic/sysdeps.cpp, sysdeps/linux/include/abi-bits/statx.h, sysdeps/linux/meson.build, sysdeps/lyre/include/abi-bits/statx.h, sysdeps/lyre/meson.build, sysdeps/managarm/include/abi-bits/statx.h, sysdeps/managarm/meson.build
Implement `statx` function and `sys_statx` sysdep for Linux.
=> Implement statx

options/posix/generic/unistd-stubs.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/managarm/generic/file.cpp
Blocked on the Managarm counterpart as I also implement the sysdep here.
=> options/posix: Implement readlinkat

.github/workflows/ci.yml
See https://github.com/actions/runner-images/issues/9524
=> ci: Workaround GitHub actions image issues

sysdeps/managarm/generic/file.cpp
Counterpart to managarm/managarm#649.
=> sysdeps/managarm: implement EFD_SEMAPHORE

options/posix/include/netinet/tcp.h
=> options/posix: Add more tcp defines and structs

sysdeps/managarm/generic/ioctl.cpp
depends on https://github.com/managarm/mlibc/pull/1062
=> sysdeps/managarm: Implement SIOCGIFBRDADDR/SIOCGIFHWADDR

options/posix/generic/pwd-stubs.cpp, tests/posix/pwd.c
=> options/posix: implement putpwent

options/linux/generic/sys-signalfd.cpp, sysdeps/managarm/generic/socket.cpp
This PR stubs two items needed for elogind.
=> Small changes for elogind

options/posix/include/sys/sem.h
Does what it says on the tin really
=> Add sem.h defines required to build postgresql

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/ioctl.cpp
Found while trying to build `GNU Hello` and `zlib` inside Managarm
=> Some self-hosting fixes for Managarm

options/ansi/generic/time-stubs.cpp
This reverts commit 24dbb3b5a9f8494dbf2de6f4e92ff9a4d815dd43.
=> Revert "options/ansi: convert use of std::array to frg::array"

sysdeps/managarm/generic/file.cpp
Blocked on managarm/managarm#717
=> sysdeps/managarm: Implement sysconf request

sysdeps/managarm/generic/file.cpp
Blocked on managarm/managarm#636
=> sysdeps/managarm: Implement sys_reboot

options/internal/generic/sigset.cpp
=> options/internal: detect underlying type of sigset_t

options/lsb/generic/tls.cpp, sysdeps/linux/m68k/crt-src/Scrt1.S, sysdeps/linux/m68k/crt-src/crt1.S
CI revealed some problems with static builds of mlibc on m68k. This fixes these.
=> m68k: fix for static builds

README.md
Add a small introduction to the library and what we aim to achieve, plus what we currently supports.
=> readme: add short introduction

.git-blame-ignore-revs
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
=> meta: add .git-blame-ignore-revs

options/posix/generic/unistd.cpp, sysdeps/managarm/generic/file.cpp
Implement _SC_{AV}PHYS_PAGES sysconfs using the sys_sysinfo sysdep if available.
=> Implement _SC_{AV}PHYS_PAGES sysconfs

options/ansi/include/time.h, options/posix/generic/time.cpp
Part of the systemd on Linux project.
=> options/posix: Stub clock_getcpuclockid

options/glibc/generic/sys-cachectl.cpp, options/glibc/include/mlibc/glibc-sysdeps.hpp, options/glibc/include/sys/cachectl.h, options/glibc/meson.build
This is a glibc extension: https://www.gnu.org/software/libc/manual/html_node/RISC_002dV.html
=> options/glibc: Add __riscv_flush_icache()

options/rtld/generic/main.cpp
This avoids lots of unnecessary syscalls to obtain the thread ID. In particular, the TID is needed in futex locks and we need a syscall to obtain it before the TCB is set up.
=> options/rtld: Set up early TCB to cache TID

sysdeps/managarm/generic/drm.cpp, sysdeps/managarm/generic/socket.cpp
Counterpart to managarm/managarm#843.
=> Cumulated fixes

options/posix/generic/sys-mman.cpp, options/posix/include/sys/mman.h
=> options/posix: move mremap and remap_file_pages to the linux option

sysdeps/managarm/generic/file.cpp
Blocked on managarm/managarm#846
=> sysdeps/managarm: Implement sys_statfs

sysdeps/managarm/generic/file.cpp
Blocked on managarm/managarm#846
=> sysdeps/managarm: Implement sys_statx

sysdeps/managarm/generic/socket.cpp
Blocked on managarm/managarm#852
=> sysdeps/managarm: Pass through 2 additional getsockopt calls

sysdeps/managarm/generic/drm.cpp, sysdeps/managarm/generic/ioctl.cpp, sysdeps/managarm/generic/mount.cpp, sysdeps/managarm/generic/socket.cpp
This PR holds various systemd fixes.
=> Systemd fixes

options/posix/generic/sys-time.cpp, options/posix/include/mlibc/posix-sysdeps.hpp, sysdeps/linux/generic/sysdeps.cpp
This is needed for systemd, on Managarm it calls this.
=> Implement settimeofday

options/glibc/generic/getopt.cpp, tests/glibc/getopt.c
=> Add argument permutation to getopt_long(_only)

sysdeps/managarm/generic/ioctl.cpp, sysdeps/managarm/meson.build
Part of the PR group of managarm/bragi#7, managarm/bootstrap-managarm#444 and managarm/managarm#840.
=> managarm: bragi wireshark changes

sysdeps/managarm/generic/ioctl.cpp, sysdeps/managarm/generic/signals.cpp
=> Some small fixes on the mlibc side for systemd on Managarm

options/rtld/generic/linker.cpp, sysdeps/managarm/rtld-generic/support.cpp
Depends on managarm/managarm#880.
=> sysdeps/managarm: implement sys_vm_protect for rtld

options/ansi/generic/time.cpp, tests/ansi/strftime.c
=> options/ansi: implement %z specifier for strftime

sysdeps/managarm/generic/file.cpp
Depends on managarm/managarm#890.
=> sysdeps/managarm: implement sys_inotify_rm_watch

sysdeps/managarm/generic/file.cpp
mlibc side of https://github.com/managarm/managarm/pull/896
=> sysdeps/managarm: Update timerfd protocol

options/posix/generic/unistd.cpp, tests/meson.build, tests/posix/swab.c
- **options/posix: Implement swab**
- **tests/posix: Add tests for swab**
=> options/posix: Implement swab

sysdeps/managarm/generic/file.cpp
Depends on managarm/managarm#912.
=> sysdeps/managarm: handle oldvalue argument for timerfd_settime

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/socket.cpp
Depends on managarm/managarm#911.
=> sysdeps/managarm: pidfd additions

sysdeps/managarm/generic/socket.cpp
Depends on managarm/managarm#910.
=> sysdeps/managarm: pass through SO_{SND,RCV}TIMEO setsockopts

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/include/bits/errors.hpp
Depends on managarm/managarm#919.
=> sysdeps/managarm: improve sys_socket error handling

options/ansi/include/mlibc/file-io.hpp, options/glibc/generic/stdio_ext.cpp
I've implemented the __fsetlocking() glibc extension. tell me if changes are needed :)
=> options/glibc: implement __fsetlocking()

options/posix/generic/posix_stdlib.cpp
`getcwd` now implements fallback logic for when no `sys_getcwd` is present. Using `sys_getcwd` in realpath bypasses this fallback logic when such thing is not intended.
=> options/posix: make realpath use system getcwd instead of syscall

sysdeps/managarm/generic/socket.cpp, sysdeps/managarm/include/bits/errors.hpp
Depends on managarm/managarm#898.
=> sysdeps/managarm: implement sys_shutdown

sysdeps/managarm/generic/ioctl.cpp
Depends on managarm/managarm#924.
=> sysdeps/managarm: support `TFD_IOC_SET_TICKS` ioctl for timerfd

options/posix/generic/sys-stat.cpp, sysdeps/managarm/generic/file.cpp
Depends on managarm/managarm#828.
=> sysdeps/managarm: handle mode for sys_mkdirat

sysdeps/managarm/include/bits/errors.hpp
Depends on managarm/managarm#985.
=> sysdeps/managarm: convert fs protocol ESRCH error

options/glibc/include/sys/timex.h, sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/managarm/generic/sched.cpp
Some patches and stubs to the managarm sysdeps for logind enablement.
=> Logind enablement work

sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/time.cpp
This PR adds missing SignalGuards to several sysdeps and improves the error handling in sys_poll.
=> Miscellaneous fixes to the Managarm sysdeps

sysdeps/managarm/generic/entry.cpp, sysdeps/managarm/generic/file.cpp, sysdeps/managarm/generic/fork-exec.cpp, sysdeps/managarm/include/mlibc/posix-pipe.hpp, sysdeps/managarm/rtld-generic/support.cpp
Depends on managarm/managarm#1012.
=> sysdeps/managarm: use the new syscall cancellation interface

sysdeps/managarm/generic/entry.cpp
Depends on managarm/managarm#1013.
=> sysdeps/managarm: merge the thread and cancellation info shared pages
